### ISSUE TITLE
Hightlight matched item when focus-in

### ISSUE THREAD

**Issue by htatuan** [ghiden/angucomplete-alt#101]
Hi,
Can we have a feature such as: when we done a search and select an item then we focus out.  when we focus in the input field again. The autocomple will load all the results (search all without keyword) and hightlight the first item that matches the keyword

**Comment by htatuan** [comment]
This is just required by my Project. They said that it looks like user's experince. Maybe as a dropdown list

**Comment by ghiden** [comment]
Too niche. I'm closing this.
