### ISSUE TITLE
[Question] How to use angucomplete-alt in forms

### ISSUE THREAD

**Issue by tamasys** [ghiden/angucomplete-alt#102]
I'm not sure if this is a dumb question, but how do you submit a form with an angucomplete-alt field? I replaced a previous input field with an angucomplete field, and on submitting it just shows the search page with no parameters because the input has no name attribute. Manually adding a name attribute in the browser inspector and then submitting lets the input work as normal.

I've just joined a team working on an Angular codebase and I'm not hugely familiar with it, so I'm not sure if there's something obvious I'm missing, or if I'm trying to do something that angucomplete wasn't designed for. Thanks!

**Comment by ghiden** [comment]
I'm guessing this has been solved.
