### ISSUE TITLE
focus-out not firing

### ISSUE THREAD

**Issue by nbunney** [ghiden/angucomplete-alt#104]
I am a little mystified and maybe it is something I am doing wrong by recently (an update?) the focus-out function is not firing at all.  I have been running on 0.3.1 and in my debugging have updated to 0.3.3.   Here is what I have, pulling directly from the DOM.

`<angucomplete-alt id="ex1" input-class="nMatType" placeholder="Fertilizers" pause="100" selected-object="CF.materialAuto" local-data="fertilizers" search-fields="name" title-field="name" minlength="1" focus-out="focusOut()" class="ng-isolate-scope">`

Besides the focus-out not working everything else appears to be working just fine.  Have I done something wrong?  I have gone so far as to try editing the hideResults function in the module to see if a console.log will fire but nothing of the sort is happening.  Any help appreciated.

**Comment by ghiden** [comment]
@nbunney Is it still happening? Just released v0.0.34 now. Could you take a look?

**Comment by nbunney** [comment]
Hi, I will be back on that project later today.  Will keep you posted.

Nathan Bunney
209-765-1262

**Comment by nbunney** [comment]
Hi,

I had bower pull the latest version and I am still having this issue.  This
worked before then just stopped working.

Nathan Bunney
209-765-1262

**Comment by ghiden** [comment]
What about the example 12 http://ghiden.github.io/angucomplete-alt/#example12
Is this working? If so, it's not this directive. Probably something wrong with your setting.

**Comment by nbunney** [comment]
Yah, that works fine for me...

Anything obvioiusly wrong with this?

angucomplete-alt(id="ex1", input-class="nMatType", focus-out="setFert()",
selected-object="CF.materialAuto", local-data="fertilizers",
search-fields="name", title-field="name", minlength="1")

I have defined $scope.setFert = function in the route for the page in
question but I never see it fire.  Are there anythings internal that I can
check to see where the problem is?


Nathan Bunney
209-765-1262

**Comment by xmark** [comment]
Im actually having the same issue... I cannot see the difference between my code and the example code, but the event never fires... I have been looking through the event handlers on your example page and my own and the blur event on the actual rendered input fields are different.

It seems that on my site, the blur event is hooked up with Jquery, but on your example page I can see that the blur event is angual bound.

But I dont know how to control this... thought it might be of help to resolve??

-- Mark

**Comment by ghiden** [comment]
If you guys can create a plnkr or jsbin or whatever example, I can take a look at it.

**Comment by nbunney** [comment]
One difference is that your code is <div angucomplete-alt and mine is <angulcomplete-alt not sure what would cause that difference.

**Comment by xmark** [comment]
Im finding it hard to isolate why, but I have also noticed that in my usage, the ng-focus event is firing twice!

**Comment by wcmiller** [comment]
Do you guys have Angular Batarang installed? I was having a similar issue, and it was [being caused by Batarang](http://stackoverflow.com/questions/27804949/ng-focus-firing-twice-and-ng-blur-never-fires).

**Comment by rodikh** [comment]
Can confirm @wcmiller. I had the selected-object function firing twice. turning off Batarang fixed it.
