### ISSUE TITLE
searching again when click on the input in angucomplete-alt

### ISSUE THREAD

**Issue by trangchuvn** [ghiden/angucomplete-alt#105]
Hello everybody!
The First, Thank you for your angucomplete-alt plugin, it's very helpful. But i have a problem, please help me.
When I press any key such as "table", it's will show a Dropdown with result. It's nice. But when i focus outside the input, the Dropdown hidden. And i focus in the input again, it's not show Dropdown again. How do we show it again. Or how do we make it not hidde when i focus outside the input.
Please help me. Many thanks. Sorry because my English is not good.

**Comment by htatuan** [comment]
I can do this by add focusIn event.but i can not to hightlight  or scroll to that item

**Comment by trangchuvn** [comment]
Really! Can you help me?

**Comment by htatuan** [comment]
I'm seaching more to implement it. It's not really good at this moment. I'm trying to hightlight and scroll to the item that selected before focusing out

**Comment by trangchuvn** [comment]
OK. Thanks for your reply. If you can do it, it's really nice :+1: 
And when you had completed, please share for me. Many thanks.

**Comment by htatuan** [comment]
Ok. But  i can show the dropdown again as you want when focusin. I will send it to you tomorrow. I left my code at company

**Comment by trangchuvn** [comment]
Thank for your help :+1:

**Comment by htatuan** [comment]
I forgot it. Sorry. Tomorrow !

**Comment by htatuan** [comment]
function focusinHandler(event) {

               if (scope.searchStr.length >= minlength) {
                    initResults();
                    if (searchTimer) {
                        $timeout.cancel(searchTimer);
                    }
                    scope.searching = true;
                    searchTimer = $timeout(function () {
                        searchTimerComplete("");
                    }, scope.pause);
                }
                if (validState && validState !== scope.searchStr && !scope.clearSelected) {
                    callOrAssign(undefined);
                }
            }
inputField.on('focusin', focusinHandler);

Just add this code.

**Comment by trangchuvn** [comment]
Thank you for your help. But when i focus in the Input, it only show searching..., but not show the results :(
Like this
http://i1112.photobucket.com/albums/k490/trangchuvn_2000/Untitled-1.png

**Comment by htatuan** [comment]
It works from my side. I just customed a litle bit. I think it also works with you Because i can ses the hint text "searching..." This means that it is working  . Have you handled the case that will search all with empty keyword ??.

**Comment by trangchuvn** [comment]
this is my code
<code>
<div angucomplete-alt placeholder="Search product" initial-value="{{item.summary.name}}" field-required="true" input-changed="inputProductChanged" pause="100" ng-click="getIndexPro($parent.$index)" selected-object="productSelected" remote-url="{{data.site}}restapi/searchproduct/{{getIdProduct()}}/{{item.summary.productId}}/" remote-url-data-field="items" search-fields="name,code" title-field="name" description-field="code" minlength="1" input-class="form-control" input-changed="inputCountryChanged" match-class="auto-highlight" text-searching="Searching..." text-no-results="Not found">
</div>
</code>

**Comment by trangchuvn** [comment]
this is my code
```html
<div angucomplete-alt placeholder="Search product" initial-value="{{item.summary.name}}" field-required="true" input-changed="inputProductChanged" pause="100" ng-click="getIndexPro($parent.$index)" selected-object="productSelected" remote-url="{{data.site}}restapi/searchproduct/{{getIdProduct()}}/{{item.summary.productId}}/" remote-url-data-field="items" search-fields="name,code" title-field="name" description-field="code" minlength="1" input-class="form-control" input-changed="inputCountryChanged" match-class="auto-highlight" text-searching="Searching..." text-no-results="Not found">
</div>
```

**Comment by htatuan** [comment]
try to set minlength to 0, can this Url get data with empty keyword ?

**Comment by trangchuvn** [comment]
i'm sorry, i was tried set minlength to 0 and edit Url can get data with empty keyword, but it is also not working :(.

**Comment by ghiden** [comment]
You are basically asking for changing the typical behavior of autocomplete. I'm sorry. Autocomplete does not work that way. You have to create your own.

**Comment by CamelCoder** [comment]
Hi, @trangchuvn  I;m meeting the same problem now , did you resolve it? If you do not mind, can you share it to me? Thanks a lot.

**Comment by CamelCoder** [comment]
@ghiden Hi how to solve this problem? Could you please tell me? Thanks very much.
