### ISSUE TITLE
How to show a suggestions list when input field is empty ?

### ISSUE THREAD

**Issue by ghiaia** [ghiden/angucomplete-alt#107]
I need to show a list of values before user enters any char in input fields (empty and just focused).
Values come from an history of recents, so user can reuse before searching.
Is it possible ? How ?
Thanks

**Comment by elifio** [comment]
1+

**Comment by Kisama** [comment]
Set minlength "0" and down arrow. You can show all list with empty search
text

**Comment by elifio** [comment]
Not work for me.
I want to show all results (7 names in the example)
I set the length to 0 and key pressed down (maybe not know any names)

you can show in this plunker with the last version 

http://embed.plnkr.co/BrHLIVysK71qr2ghZ4fT/preview

**Comment by Kisama** [comment]
I need to check version that I used tomorrow.
I think maybe I use older version,

I check the current source and found there are some validation logic to
prevent search with empty string.



2015-02-03 21:43 GMT+09:00 elifio <notifications@github.com>:

**Comment by tamilp** [comment]
Yes, minlength = 0 not working, what is the solution ?

**Comment by tamilp** [comment]
i was done for my own, whether it is right or wrong don't know but finally worked for me

1. set minlength = 0;
comment the below code in your angucomplete-alt.js file
2. its around 255 line
    ......
          else {
            /*if (!scope.searchStr || scope.searchStr === '') {
              scope.showDropdown = false;
            } else*/ if (scope.searchStr.length >= minlength) {
              initResults();

              if (searchTimer) {
                $timeout.cancel(searchTimer);
              }
    .........
3. around 489 line
............
        function searchTimerComplete(str) {
          // Begin the search
          /*if (!str || str.length < minlength) {
            return;
          }*/
          if (scope.localData) {
            scope.$apply(function() {
              getLocalResults(str);
            });
          }
..........

**Comment by tamilp** [comment]
i was done for my own, whether it is right or wrong don't know but finally worked for me

1. set minlength = 0;


2. Comment the below code in your angucomplete-alt.js file, around 255 line

          else {
            /*if (!scope.searchStr || scope.searchStr === '') {
              scope.showDropdown = false;
            } else*/ if (scope.searchStr.length >= minlength) {
              initResults();

              if (searchTimer) {
                $timeout.cancel(searchTimer);
              }
			  
3. Comment the below code in your angucomplete-alt.js file, around 489 line

        function searchTimerComplete(str) {
          // Begin the search
          /*if (!str || str.length < minlength) {
            return;
          }*/
          if (scope.localData) {
            scope.$apply(function() {
              getLocalResults(str);
            });
          }

**Comment by ghiden** [comment]
I never implemented this as I thought showing a list without any input feels wrong for autocomplete. I'll think about this.

**Comment by ghiden** [comment]
I just want to make sure the problem here. This feature is to show all items when user focus on the input field rendered by this directive, right? And, this is only valid for local data, correct? In other words, I don't think that the remote API returns all results with supplying query term of what? So, I think this is only useful or usable for local data. Am I correct?

**Comment by winiciuswanderlei** [comment]
Correct, at least to my point of view.

**Comment by ghiaia** [comment]
In absence of user indications (input field void) the remote server can
produce a initial list of "suggestions", ie a list of tipical choices
(based on history, other fields values or something else usefull to guide
the user to an immediate easy response)
This list is preloaded on init or on change in other input o event.
When user types something (instead of select from the list) the usual
typeahead list substitues the first.

2015-03-26 9:51 GMT+01:00 Hidenari Nozaki <notifications@github.com>:

> I just want to make sure the problem here. This feature is to show all
> items when user focus on the input field rendered by this directive, right?
> And, this is only valid for local data, correct? In other words, I don't
> think that the remote API returns all results with supplying query term of
> what? So, I think this is only useful or usable for local data. Am I
> correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ghiden/angucomplete-alt/issues/107#issuecomment-86407740>
> .
>



-- 
Marco Vaccari

Vaccari A. Giulio S.p.A.
Via Chemello, 12/D
I36075 Montecchio Maggiore
VICENZA ITALY
xx39-0444-492330 (tel)
xx39-0444-694747 (fax)

**Comment by winiciuswanderlei** [comment]
Here ran as follows, creates a function:

scope.nameFunction = function () {
  processResults(scope.localData, '');
  scope.showDropdown = true;
}

On line 51 in input add the even ng-click="nameFunction()':
'  <input ng-click="nameFunction()" ...

I do not know if it's the right way but it worked for me.

**Comment by ghiden** [comment]
Released in v0.0.38
