### ISSUE TITLE
Dynamic control the input

### ISSUE THREAD

**Issue by pitymaia** [ghiden/angucomplete-alt#108]
I can't get any control over the input, to clear i need use a brodcast, but if i want reset to the last selected option or make the selection dynamic thru angular or pure javascript?
Any atempt to change the values result in a BUG, the value change, but when the input get focus out the old value back to the input.
Why i can't have control over the input? Why i can't be able to set values to the input?

**Comment by ghiden** [comment]
Sorry, I guess this directive is not suitable for what you need.
You get simplicity by not having control over the input.
This is just by design.

**Comment by mgardner-git** [comment]
It would be nice if we could have a two way binding on one of these directives.  For example if I use selected-object="reservation" and ng-model="reservation.name", then, some other event modifies reservation.name, the input should show that new value.
