### ISSUE TITLE
Know is suggestions were overriden

### ISSUE THREAD

**Issue by blackotruck** [ghiden/angucomplete-alt#112]
Greetings!

Currently i'm usin this awesome library in a project... Now, is there a way to know that the suggestions has been overriden. I'm in the need of this, because the model that i'm gonna send to the server is different depending on the fact that the value correspond with the response-data or not something like:

```
if(suggestions_overriden){
   var data = {model_A:object};
} else {
   var data = {model_B:object};
}

$http.post({url:url, data:data}):
```

As you can see even if the data is the same, the name of the model change, and this is very important.

Anyone knows a way arround?

**Comment by ghiden** [comment]
In two-way binding case, if selectedObject contains 'originalObject', that means it is not overridden.
In callback case, if the argument contains 'originalObject', that means it is not overridden.

**Comment by blackotruck** [comment]
Thanks for the answer, but actually the 'originalObject' is always present, but, what i did was check the type, so if it is an 'object', then is a selected option, otherwise is overridden

**Comment by ghiden** [comment]
Yep, you are right. Sorry I was just recalling from my memory. Anyway, you got it.
