### ISSUE TITLE
Actions on the results items

### ISSUE THREAD

**Issue by blackotruck** [ghiden/angucomplete-alt#114]
Hi! 

I'm using the angucomplete input not as a select but to show results and allow the user to do actions on top of said results (like the send friend request on the facebook search bar). Is there a way to add actions on the results elements? I also need to add filters to format some strings on the results

**Comment by ghiden** [comment]
Nope, this is nearly impossible. If you use custom template, you may be able to implement it but I don't think it's worth your effort.

**Comment by blackotruck** [comment]
@ghiden I did use a custom template and added a directive that shows a popup on hover wich allows me to do different actions. Now, my issue is that when i click on the popover the result dissappear, i would like to prevent that form happen, and only close the result when my actions are done (or i click outside the result and/or the popover)

**Comment by ghiden** [comment]
Oh you actually use the template and made it almost work, good for you. Once your popover is shown, this is your directive's territory. You probably need to implement a click out handler in your popover directive.

**Comment by blackotruck** [comment]
the clickout handler on the directive is working to, the issue here is that clicks inside the directive cause the result to dissappear, even while the popover is still visible

**Comment by ghiden** [comment]
Could you create a jsbin or plnkr so that I can take a look?

**Comment by blackotruck** [comment]
OK, i'll try to do it on the weekend, stay tuned
