### ISSUE TITLE
Clear search box after successful search using a button

### ISSUE THREAD

**Issue by kcijeziefairsailcom** [ghiden/angucomplete-alt#116]
How do clear the search box after a successful search using a button? Like fire an ngClick function to clear the search box?

**Comment by blackotruck** [comment]
You can clear the input with the 'focus-out' attribute, there is no need for a button. Just pass a function like:
```
$scope.clearSearch = function(){
   $scope.$broadcast('angucomplete-alt:clearInput');
}
```

**Comment by kcijeziefairsailcom** [comment]
Thanks. Will give it a go!

Sent from my BlackBerry 10 smartphone on the O2 network.
From: Jesús Ugueto
Sent: Thursday, 29 January 2015 12:16 PM
To: ghiden/angucomplete-alt
Reply To: ghiden/angucomplete-alt
Cc: KC Ijezie
Subject: Re: [angucomplete-alt] Clear search box after successful search using a button (#116)



You can clear the input with the 'focus-out' attribute, there is no need for a button. Just pass a function like:

$scope.clearSearch = function(){
   $scope.$broadcast('angucomplete-alt:clearInput');
}


-

**Comment by fproldan** [comment]
Thanks, works for me too.

**Comment by ghiden** [comment]
I think this is solved. Thanks, @blackotruck.
