### ISSUE TITLE
Another image-field value

### ISSUE THREAD

**Issue by levipadre** [ghiden/angucomplete-alt#117]
Hi,

This directive is really cool, thanks!
I'm using the custom template and it's working perfectly.
Is it possible, that use a second image-field value or create an if statement, which is depends on one of the data value? Just because the json datas is not always the same.
E.g.
```
"results": [
   {
      "animal_image_path": "/animal1.jpg",
      "type": "animal"
   },
   {
      "human_image_path": "/human1.jpg",
      "type": "human"
   }
],
```

In this case I need this one:
```
image-field="animal_image_path,human_image_path"
```
or something like this
```
if ("type" == "animal") {image-field="animal_image_path"} else {image-field="human_image_path"}
```

Is it possible somehow?

Thanks,
L

**Comment by ghiden** [comment]
This is not possible. But if your data is remote, you can use remote-url-response-formatter to add a unified image attribute.
