### ISSUE TITLE
escape the RegEx 

### ISSUE THREAD

**Issue by iamgurdip** [ghiden/angucomplete-alt#123]
RegEx needs to be escaped in 'findMatchString' function, otherwise if the input value has parenthesis (or other RegEx syntex) it causes errors.

Use the below to fix(notice line#1)

`function findMatchString(target, str) {
                      str = str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); 
                      var result, matches, re = new RegExp(str, 'i');
                      if (!target) { return; }
                      matches = target.match(re);
                      if (matches) {
                          result = target.replace(re,
                              '<span class="' + scope.matchClass + '">' + matches[0] + '</span>');
                      }
                      else {
                          result = target;
                      }
                      return $sce.trustAsHtml(result);
                  }`

**Comment by ghiden** [comment]
@iamgurdip Good catch! Thank you. I'll fix it with your suggestion.
