### ISSUE TITLE
Dropdown Wont Leave

### ISSUE THREAD

**Issue by CMDann** [ghiden/angucomplete-alt#125]
I did some searching and I didn't see any other issues here. I am trying to implement this and so far it is really awesome, however I am running into a visual issue. 

![screen shot 2015-02-23 at 12 44 32 pm](https://cloud.githubusercontent.com/assets/4128000/6334376/e6f660d0-bb59-11e4-8380-b57bb4e290dd.png)

As you can see the "Searching" and "No results found" boxes never go away, if I am searching it does properly work it just seems to not hide this. My div looks like this:

<pre>
angucomplete-alt id="ex7"
placeholder="Search Picticipators"
pause="100"
selected-object="picticipator_selected"
local-data="picticipators"
search-fields="name"
title-field="name"
minlength="1"
input-class="form-control form-control-small"
match-class="highlight"
focus-in="focusIn()"
focus-out="focusOut()"
</pre>

I have also implemented this within my app,js

<pre>
var modules = [
    'ngRoute',
    'ngTouch',
    'infinite-scroll',
    "checklist-model",
    "ui.bootstrap",
    "angucomplete-alt"
];
</pre>

It is probably a stupid issue but I appreciate any help I can find. Has anybody else encountered this? I am using the latest version.

**Comment by ghiden** [comment]
Could you create a jsbin or plnkr? I need to see it in action.

**Comment by ghiden** [comment]
@CMDann Are you still having this issue?

**Comment by ghiden** [comment]
No response, closing this for now.
