### ISSUE TITLE
Installing from NPM - example is not plug and play

### ISSUE THREAD

**Issue by juliusakula** [ghiden/angucomplete-alt#133]
There's a few issues that I had to fix before the example file worked. When I do 'npm install _package_' I expect to go into the example folder and be able to run the examples instantly, and I wanted to make it known what needs to be fixed:

###### Line numbers refer to example/index.html

1. this package is not self-containing, and doesn't contain any node_modules folder, therefore angular.js was not included correctly in the example/index.html initially. In my case, I am on an httpS apache server and lines 293 and 294 failed to load, couldn't fetch from http: while on https. Perhaps nitpicky, but npm packages tend to themselves have node_modules folders.

2. the .js file 'js/libs/angucomplete-alt.js' file referenced in line 295 DNE, that should instead point to '../angucomplete-alt.js'

3. the .css file 'css/angucomplete-alt.css' referenced in line 11 DNE, it should point to '../angucomplete-alt.css'

4. angular and ~~angular-touch~~ ngTouch are not listed as devDependencies in package.json

I can create a pull request for these issues but not at this moment in time, perhaps tonight

**Comment by ghiden** [comment]
Updated README about how to run examples.
