### ISSUE TITLE
Search by one field, but insert another field in the input

### ISSUE THREAD

**Issue by ctilley83** [ghiden/angucomplete-alt#135]
Needs the ability to search by a field name, but after selecting, insert only another field of your choosing into the input box.  Another way you could accomplish is the ability to select a hidden field.

**Comment by ghiden** [comment]
Not sure what you are asking for. But hidden field can be added outside of this directive. So, I don't think it is necessary for this directive to have a feature for adding a hidden field.

**Comment by ctilley83** [comment]
Can you access the response data that angucomplete requests from the remote server, so I wouldn't have to fetch additional attributes?

The feature is necessary, I've used the feature in a rails autocomplete gem.  They call that field :display_value so you can search by one term for example a :name field, and input the :id field in the text box when you select the name.  It's good for selecting a one to many relationship.

**Comment by ghiden** [comment]
I'm still not sure what you are tryng to do but maybe if you want to access the raw data and format however you like is remote-url-response-formatter. By providing a function to that, it can access the raw data and manipulate the data then it gets shown to the user.

**Comment by ctilley83** [comment]
English isn't your first language is it?

**Comment by ghiden** [comment]
Nope.

**Comment by Boshen** [comment]
You can use the `title-field` attribute to display the `id` after selecting an item from the dropdown.

To access the response data, you can provide a function to the `selected-object` attribute.

**Comment by ctilley83** [comment]
Piddling with the title-field, that determines what is visible in the dropdown.  So if I want to search for certain fields, title-field determines that correct?

**Comment by Boshen** [comment]
`title-field` is for display only.

You need to use the `search-fields` attribute for searching.

So in your case my guess is that you have to do
```
title-field="id"
search-fields="name"
```
Where you data array is
```
[{ id: 1, name: 'name'}...]
```

An example has already been given:
https://github.com/ghiden/angucomplete-alt/blob/master/example/index.html#L53
http://ghiden.github.io/angucomplete-alt/#example1
