### ISSUE TITLE
dropdown automaticaly hided when scroll on touch device

### ISSUE THREAD

**Issue by vulcaryn** [ghiden/angucomplete-alt#137]
Hello,

Thanks for your great work: 
I have an issue when i try to limit the height of the dropdown with a touch device (Surface pro 3).
When i try to scroll le list of result, the dropdown are immediately closed. After a little investigation, I think the problem come from the event triggered on mousedown and more particularly, the value of event.target.id. 
This problem doesn't exist when i use a mousewheel but without wheel, mousedown is triggered to slide.
I have found a tricky solution with 2 steps: 
 - When mousedown is triggered and event.target.id empty, set mousedownOn with event.target.className
 - In the hideResults method check if "angucomplete" are in the mousedownOn

I hope this tricky solution help you to find a more pretty solution.

Thanks

**Comment by horowitz2009** [comment]
Hello,
I have the same problem and it occurs on PC (Chrome browser). Having a lot of results and scrollbar displayed, clicking on any part of the scrollbar (Up arrow, Down arrow or the the scrollbox) closes the dropdown.

Thanks.

**Comment by horowitz2009** [comment]
Ok. I need to add some info. It appears that it happens if input field is part of modal window. Otherwise it's working just fine.

**Comment by horowitz2009** [comment]
Here's the thing. If directive used in modal window, bug is there. In normal page, with property `id`set, the bug is there. With no `id` set, it works fine.

**Comment by ghiden** [comment]
@horowitz2009 Is this happening on Chrome on Windows? Is it Surface pro 3? What modal system are you using?

**Comment by horowitz2009** [comment]
Yes, It is Windows, Chrome Version 43.0.2357.124 m. 
and part of my dependencies list:
    "bootstrap": "~3.3.4",
    "angular": "1.3.x",
    "angular-animate": "1.3.x",
    "angular-ui-router": "~0.2.13",
    "normalize.css": "~3.0.2",

**Comment by ghiden** [comment]
@horowitz2009 Thank you.
I'll try to prepare an example solution for you to try.

**Comment by ghiden** [comment]
I just release a new version. This might have fixed this issue.
@horowitz2009 Please try them http://ghiden.github.io/angucomplete-alt/

**Comment by horowitz2009** [comment]
Hi, I tried the new version with my stuff and it works. 

Thanks.
