### ISSUE TITLE
Expected JSON return format Question

### ISSUE THREAD

**Issue by ctilley83** [ghiden/angucomplete-alt#139]
AnguComplete successfully requests data from the server and responds with the following JSON object.  However Angucomplete still responds with "result not found".  I'm assuming the JSON return is not formatted in the correct way. Any ideas?

    {"clients":[{"company_name":"Wal-Mart","id":17}]}

My angucomplete directive looks as follows:

       <angucomplete-alt id="client_id"
                                      placeholder="Search clients"
                                      pause="400"
                                      selected-object="clientSelected"
                                      remote-url="/clients/getClients?term="
                                      remote-url-data-field="clients"
                                      title-field="company_name"
                                      description-field="company_name"
                                      input-class="form-control form-control-small">
          </angucomplete-alt>

**Comment by ghiden** [comment]
It looks good to me. But @ctilley83 won't probably understand my English. So, @Boshen, could you reply to him?

**Comment by ctilley83** [comment]
lol. smartass

**Comment by ctilley83** [comment]
In all seriousness though. Do you have any ideas why the dropdown isn't populating?

**Comment by ghiden** [comment]
Could you paste the raw response from your server?

**Comment by ctilley83** [comment]
I'm using rails so here is my console output

    Started GET "/clients/getClients?term=wal" for 127.0.0.1 at 2015-03-26 15:44:17 -0400
    Processing by ClientsController#getClients as JSON
      Parameters: {"term"=>"wal"}
      Client Load (0.4ms)  SELECT company_name,id FROM `clients` WHERE (company_name LIKE '%wal%')
    Completed 200 OK in 14ms (Views: 12.5ms | ActiveRecord: 0.4ms)

**Comment by ghiden** [comment]
Could you get the response from dev console on your Chrome?

**Comment by Boshen** [comment]
Alright let me translate, @ghiden wants the *raw response*, i.e. what the server sends to the client. You pasted the console output, which is the input to the server.

**Comment by ctilley83** [comment]
Remote Address:[::1]:3000
    Request URL:http://localhost:3000/clients/getClients?term=walk
    Request Method:GET
    Status Code:304 Not Modified
    Response Headers
    view source
    Cache-Control:max-age=0, private, must-revalidate
    Connection:Keep-Alive
    Date:Thu, 26 Mar 2015 19:58:15 GMT
    Etag:W/"0488bd9941b8a6f20bdee349deb965cd"
    Server:WEBrick/1.3.1 (Ruby/2.2.0/2014-12-25)
    X-Content-Type-Options:nosniff
    X-Frame-Options:SAMEORIGIN
    X-Request-Id:e6777420-579a-47ca-9b4f-e108fa4ac132
    X-Runtime:0.015653
    X-Xss-Protection:1; mode=block
    Request Headers
    view source
    Accept:application/json
    Accept-Encoding:gzip, deflate, sdch
    Accept-Language:en-US,en;q=0.8
    Connection:keep-alive
    Cookie:request_method=GET;     _stone_dynamics_session=VTRrRGdMMVI4YlgvV1pqam1OQkxmTTJTdmFJcjJkMnNoRU1hbGtNZjd6S0FDbG1VNUNsKzJvVTJrbEV4dmNKMU83c2xLOFhLUjlVUmdTZXJWZHZGRWd6VFFOOHg4ZjJITFhCeVNUYUNEV3V2b0F0T2NkcTI5T0l2UzBLaEdFTFAxa2tzRC9oYTd5YzBXVFd6bWVVN3JFL1NkczdaZTNlbVZLTE5yTThzMG91MXdOSGY1bHk1d0ZvLzF4UURFMm5kNjAySTZjcU1EdlpZU1F6NFJhcXRUbWRmMmh6YWNIZjV5NVVSMEZXQ3A4Q0lmWEQyblBrdmprQVM4UldMMWZVWGx4WWdOSHdIbFhmNDJwdTRtc3E3dWc9PS0tYXJvd25XcG4xN25yWjlyUnowdnhEZz09--be261ad2674daa0f2cb327c12035abf17ac2aba0; _angularails_session=MTRQRzFZMUw2Z0lLTU1ZQlB1dTFQWnQrZk5tQUt2cFpEWWo0YnBleWpLVlIwaHdWWG5xR2M3ZnBiTDNLM0FEODFXN1dBbUhsTFVzSzRIdEROSEJNT0xQY3AzbTFJT3padjhGRDNWVVk5RGVzWFZTOC9NODNYdHREam85YWhicXVRZzVITExBdkhrUDZtVmp2SVIxVzFnPT0tLXZKc0ZzYXhpZmxCNWFzcFBWNHI0OHc9PQ%3D%3D--5fe2a9aecb51464986927553deecff105f71659d; XSRF-TOKEN=DT5c_gw4dwId4Du6lNK1hS7m; connect.sess=s%3Aj%3A%7B%22passport%22%3A%7B%22user%22%3A%2254f9c79ae4b0963cb5be6926%22%7D%2C%22_csrf%22%3A%22DT5c_gw4dwId4Du6lNK1hS7m%22%7D.38tKdWiWwomfUlXwtkiQ7sRRX%2BSZsk0ZyqwIijY0uYc; __ngDebug=true; _cwi2_session=cmRIV3JKWXdlM1h0L0d2cjRsUTEyVkZSVTFZWm40ZXZ1cXZPRmlZN0xNQi9wWjlPNUx5Z0E0N0FZYUMyQVZyRXk5a2tJRDdaZk85b0NIalhCTklMV3hoMjFlb2tDNGYzeDNXUFhTaUlBRkZNbDVzYTJNRmg1OXFnOGN1VXplN3U1UHo4OFRtdll4Q3JjQjlTcVgrTnJBPT0tLTlhanROTlErQzl3c204cZ2YjVYL2c9PQ%3D%3D--c972dc987b64f5c9404297b06490cdacf3433f10
    Host:localhost:3000
    If-None-Match:W/"0488bd9941b8a6f20bdee349deb965cd"
    Referer:http://localhost:3000/products
    User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36
    X-CSRF-Token:cAkgI9DCMA8MmJ7tvmZEqR9JKReCiXhmohQf8wZZ+OzjX3CK9FDioGPUKdeKr6AxB1EBqrQE    GDAjh8et9gzQkw==
    X-XSRF-TOKEN:DT5c_gw4dwId4Du6lNK1hS7m
    Query String Parameters
    view source
    view URL encoded
    term:wal

**Comment by ghiden** [comment]
These are headers. Click on 'Response' tab and grab it, please.

**Comment by ctilley83** [comment]
This is what is in the response tab:   
    {"clients":[{"company_name":"Wal-Mart","id":17}]}

**Comment by ghiden** [comment]
Now, I have no clue seriously. It looks all fine to me.

**Comment by ctilley83** [comment]
I'll start from scratch and see if that helps.  Problem seems like it's on my end.  I appreciate the help guys.  Sorry for the confusion.

**Comment by ctilley83** [comment]
Got it working.  Apparently the gem `angular-rails-templates` was out of date.  running `bundle update` fixed the problem

**Comment by ghiden** [comment]
Great!
