### ISSUE TITLE
Issue with selected-object. Can you explain in more detail.

### ISSUE THREAD

**Issue by ctilley83** [ghiden/angucomplete-alt#143]
I'm running into unexpected behavior.  My application is strictly CRUD based.  When I set selected-object to the model scope in my `products`  controller, I run into an issue where angucomplete clears my input fields when updating records.  I created an `edit()` function which populates the input fields for a certain product.  When I update the field which is an autocomplete field, it clears all of the input fields for that product.

I have partially worked around the issue by setting `selected-object` to it's own name.  I can then assign it  to my scope variable using something to the extent of: 

`$scope.product.client_id = $scope.clientAutocomplete.originalObject.id`

and setting the `initial-value` to `{{  product.client_id  }}`

The problem with this method is if I don't modify the autocomplete field on edit, I get the error that angucomplete object is undefined.  It would be nice if setting `initial-value` would create an object so this error isn't encountered. 

It would also be nice if further explanation on `selected object` were given.  It would be beneficial to explain this functionality for applications that `create` and `update` a lot of records.

P:S: Ghiden, your english is good, mine probably isn't :)

**Comment by Boshen** [comment]
| Attribute        | Description           | Required | Example  |
| :------------- |:-------------| :-----:| :-----|
| clear-selected | To clear out input field upon selecting an item, set this attribute to true. [example](http://ghiden.github.io/angucomplete-alt/#example3) | No | true |

**Comment by ctilley83** [comment]
I applaud your effort, but that's not what I asked.  All that does is clear the autocomplete field on select.  Here's a video that shows the behavior I'm getting.

https://www.youtube.com/watch?v=x8D3QnGIhGI&feature=youtu.be

**Comment by Boshen** [comment]
Wow thank you for the video.

Now if you read the description of the `selected-object` carefully:
> selected-object - Either an object in your scope or callback function. If you set an object, it will be two-way-bound data as usual. If you set a callback, it gets called when selection is made.

You wrote `selected-object="product"`, which means upon selecting an item from the dropdown, you replaced the entire `product` object.

What you should do instead is something like `selected-object="selectProduct"`, where
```
selectProduct = (selectedObject) ->
  $scope.product.?? = selectedObject.originalObject.??
```

You were almost there. Good luck.

**Comment by ctilley83** [comment]
I really appreciate it.  I'm new to Angular coming from the Rails world.  Rails makes a great backend to angular, but grasping the concepts has been a little challenging.

**Comment by jgotthel** [comment]
I used a watch on the output value.
selected-object="output"
$scope.$watch('output', function (val) {
      //do Somethig
});

**Comment by laioviana** [comment]
Thank jgotthel had same problem and got it done with de $scope.$watch!
