### ISSUE TITLE
Empty field type when not specifying

### ISSUE THREAD

**Issue by viebig** [ghiden/angucomplete-alt#147]
I had a problem with Parsley validation plugin regarding the absense of the type in the dynamic generated input. 

Maybe when not defined set it as 'text'.

check [the issue](https://github.com/guillaumepotier/Parsley.js/issues/856)

**Comment by ghiden** [comment]
Is this still an issue?

**Comment by ghiden** [comment]
No response, closing this.

**Comment by viebig** [comment]
Well.. If it isnt fixed probablybstill an issue
