### ISSUE TITLE
suggest some features

### ISSUE THREAD

**Issue by alakip** [ghiden/angucomplete-alt#148]
Thank you for your great job,
I have a question, Is it possible to add some feature in remote data mode that directive could returns a key field value instead of the root object? (for example one of the search fields such as id or ...). In this situation I think if directive could accept a key field value as default value, then for a 2-way binding, directive could search by id in remote data and can initial the result record as selected item or default value.

Thanks.

**Comment by Boshen** [comment]
This seems to be for a specific use case, at this point I would just fork the repo and implement my own version.
