### ISSUE TITLE
Is it possible to select multiple values?

### ISSUE THREAD

**Issue by beradrian** [ghiden/angucomplete-alt#150]
Is it possible to have an input field where to enter multiple values? This would have to be submitted in the form as values under the same parameter name.

**Comment by ghiden** [comment]
Nope. This is not select element.

**Comment by beradrian** [comment]
Select wasn't probably the best word. I was thinking if it's possible to enter multiple values. After you selected a value from the dropdown to be able to input data again in the field.

**Comment by ghiden** [comment]
I see what you meant. Yes, it is possible. It's just a matter of how you structure html and style. Basically you need to have a container and have this angucomplete as input directive as float element. Every time an item is selected, you create a div or something with the selected value and appended before the input directive. It's a bit of work but just a matter of DOM manipulation of right css styling.
