### ISSUE TITLE
Bug with minlength="0"

### ISSUE THREAD

**Issue by Boshen** [ghiden/angucomplete-alt#151]
With `minlength="0"`, the drop down menu disappears when you do the following steps:
1. click on the input (the drop down appears)
2. type something that will return a match
3. clear the input (the drop down shows the whole list again)
4. hover over the drop down (and it disappears)

There seems to be another bug related to this. Again with `minlength="0"` and also using local data. If you type something that doesn't return a match, and then clear the input, it sometimes shows
```
Searching...
Item 1
item 2
```

**Comment by ghiden** [comment]
@Boshen Thank you for reporting this.

**Comment by Boshen** [comment]
Oh wow that was fast! Thank you!

**Comment by ghiden** [comment]
Because I owe you a lot. You've been handling all those issues. Thank you too.
