### ISSUE TITLE
Allow setting http headers on requests

### ISSUE THREAD

**Issue by alias1** [ghiden/angucomplete-alt#152]
I had a look, and it doesn't seem it's currently possible.

It would be REALLY useful if we could specify http headers to be sent along with the request (notably for authentication)

**Comment by Boshen** [comment]
If it is for authentication purposes, shouldn't you do the configuration at a higher level? i.e. use $http request interceptor.

**Comment by alias1** [comment]
Yeah, that is a very good point.. disregard :)
