### ISSUE TITLE
Can i trigger search on dropdown suggestion click?

### ISSUE THREAD

**Issue by pratikm23** [ghiden/angucomplete-alt#153]
Hey i want to know if its possible to trigger search with remote url and set the selected object once the suggestion from the dropdown is clicked? 

Currently its working like the suggestion gets selected and entered into the text box and i have to click the search button next to it in order to search.

**Comment by Boshen** [comment]
If I understand your problem correctly, you should be able to provide a function to the `selected-object` attribute, and then do your search inside this function.

**Comment by pratikm23** [comment]
The selected object attribute contains the selected object name : 
<angucomplete-alt id="src"
                            placeholder="Search Stuff"
                            pause="100"
                            selected-object="srcObj"
                            remote-url="stuff.php?name="
                            remote-url-data-field="results"
                            title-field="name"
                            description-field="locality"
                            input-class="form-control form-control-small"/>
 <a class="btn btn-primary" style="color:white" href=srcObj">Search</a>

Does angucomplete have something like onclick of any selected item?

**Comment by Boshen** [comment]
Just provide a callback to `selected-object`, for example
` selected-object="selectProduct"`, where
```
selectProduct = function (selectedObject) {
  $scope.product.?? = selectedObject.originalObject.??
  // do more stuff
}
```
