### ISSUE TITLE
The selectedObject is only set when you choose from the dropdown list

### ISSUE THREAD

**Issue by slj** [ghiden/angucomplete-alt#157]
If a user types a search term and doesn't select anything from the dropdown list, I think the search term should automatically become the value object once the dropdown is hidden.  Perhaps something like:
```
...
512       scope.hideResults = function(event) {
513         if (!scope.selectedObject || scope.selectedObject && /^\s*$/.test(scope.selectedObject.title)) {
514           scope.selectedObject = {
515             title: scope.searchStr,
516             description: "",
517             image: "",
518             originalObject: {
519               name: scope.searchStr
520             }
521           };
522           callOrAssign(scope.selectedObject);
523         }
...
```
This way the list becomes a true input field helper.  Furthermore, there could be a flag to force a list selection when random input is not allowed:
```
<div anguautocomplete-alt force-list-selection="true" ...></div>
```
and then:
```
 61       autoMatch: '@',
 62       forceListSelection: '@',
 63       focusOut: '&',
...
513       scope.hideResults = function(event) {
514         if (!scope.forceListSelection) {
515           if (!scope.selectedObject || scope.selectedObject && /^\s*$/.test(scope.selectedObject.title)) {
516             scope.selectedObject = {
517               title: scope.searchStr,
518               description: "",
519               image: "",
520               originalObject: {
521                 name: scope.searchStr
522               }
523             };
524             callOrAssign(scope.selectedObject);
525           }
526         } else scope.searchStr = '';
```

Thanks for your consideration, and great work!

**Comment by ghiden** [comment]
Sorry, I don't understand the intention of setting the search term to some unknown value object. Could you give us more examples that this becomes useful? The user of this directive provides a set of valid choices and why do you want to select invalid one?

**Comment by slj** [comment]
Does this example make the intention clearer? http://codepen.io/sljenifer/pen/LVbXZX

**Comment by ghiden** [comment]
Thank you for the example.
But it still doesn't make much sense to select the current search term as selected value without user's clear intention like click or enter.
We have override-suggestion option that takes the current search term when user hits enter.

Besides, this has a huge impact to existing code base as it selects invalid item to selectedObject.
Thanks for your suggestion but I'm closing this.
