### ISSUE TITLE
Using input in a form

### ISSUE THREAD

**Issue by eselmeister** [ghiden/angucomplete-alt#160]
Would it make sense to add the name field to the input element so that it can be used within a <form> tag? Expand the input element in the following way:

<input id="{{id}}_value" ...
to
<input name="{{id}}" id="{{id}}_value" ...

Or is there another way to get the selected value within a POST request?

**Comment by ghiden** [comment]
Name attribute support is released with v0.0.40 but POST is not implemented yet.
