### ISSUE TITLE
why doesn't this get converted to <input> tag when <angucomplete-alt> is written in jade

### ISSUE THREAD

**Issue by sfaizan** [ghiden/angucomplete-alt#161]
i have written a form with one of the fields as auto complete , but in the source of HTML, the angucomplete doesnt convert to a input tag( as compared to the html test code written, which converts to a input tag in source), how do i make this work using jade?? pls help

**Comment by Boshen** [comment]
Can you provide more context? i.e. your Jade code and converted HTML?

**Comment by sfaizan** [comment]
HTML here:
<!DOCTYPE html>
<html ng-app="app" ng-controller="myCtrl">

<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <script src="angular.js"></script>
    <script src="angucomplete-alt.min.js"></script>
    <script src="lodash.js"></script>
    <script src="app.js"></script>

</head>

<body>
    <angucomplete-alt 
        id="sectors" 
        placeholder="Search sectors" 
        local-data="sectors1" 
        selected-object="onSector1Selected" 
        search-fields="Sector"
        pause="300"
        minlength="1"
        title-field="Sector">
    </angucomplete-alt>

    <angucomplete-alt
        ng-show="qps.length>0" 
        id="qps"
        pause="300"
        minlength="1"
        placeholder="Search QPs" 
        local-data="qps" 
        selected-object="onQPSelected" 
        search-fields="QP" 
        title-field="QP">
    </angucomplete-alt>
</body>
</html>

This was converted to jade using html2jade.org:- 

doctype html
html(ng-app='app', ng-controller='myCtrl')
  head(lang='en')
    meta(charset='UTF-8')
    title
    script(src='angular.js')
    script(src='angucomplete-alt.min.js')
    script(src='lodash.js')
    script(src='app.js')
  body
    angucomplete-alt#sectors(placeholder='Search sectors', local-data='sectors1', selected-object='onSector1Selected', search-fields='Sector', pause='300', minlength='1', title-field='Sector')
    angucomplete-alt#qps(ng-show='qps.length>0', pause='300', minlength='1', placeholder='Search QPs', local-data='qps', selected-object='onQPSelected', search-fields='QP', title-field='QP')


And the code in the developers tools i see is (for just one angucomplete tag for now):

<angucomplete-alt id="sectors" placeholder="Search sectors" local-data="sectors1" selected-object="onSector1Selected" search-fields="Sector" pause="300" minlength="1" title-field="Sector" class="ng-isolate-scope"><div class="angucomplete-holder" ng-class="{'angucomplete-dropdown-visible': showDropdown}">  
<input id="sectors_value" ng-model="searchStr" ng-disabled="disableInput" type="" placeholder="Search sectors" maxlength="524288" ng-focus="onFocusHandler()" class="ng-valid-maxlength ng-dirty ng-touched ng-valid-parse" ng-blur="hideResults($event)" autocapitalize="off" autocorrect="off" autocomplete="off" ng-change="inputChangeHandler(searchStr)">  <div id="sectors_dropdown" class="angucomplete-dropdown ng-hide" ng-show="showDropdown">    <div class="angucomplete-searching ng-binding ng-hide" ng-show="searching" ng-bind="textSearching">Searching...</div>    <div class="angucomplete-searching ng-binding" ng-show="!searching &amp;&amp; (!results || results.length == 0)" ng-bind="textNoResults">No results found</div>      </div></div></angucomplete-alt>

Notice there is input tags auto generated by the angucomplete .but here is the output code seen in developers console of jade equivalent:

<angucomplete-alt id="sectors" placeholder="Search sectors" local-data="sectors1" selected-object="onSector1Selected" search-fields="Sector" pause="300" minlength="1" title-field="Sector"></angucomplete-alt>


there is no parsing done, or code been replaced, i've included the angucomplete-alt.min.js and its .css file properly.

**Comment by Boshen** [comment]
Sorry, I can't find anything that is wrong ...

**Comment by sfaizan** [comment]
Thanks, i somehow got it working
