### ISSUE TITLE
Using minlength="0" and auto-match="true" causes undesired results

### ISSUE THREAD

**Issue by antony** [ghiden/angucomplete-alt#162]
If you set minlength to 0 and have auto-match enabled with a local data-set, the following behaviours are exhibited:

1. Entering the field causes the dropdown to show only the first item in the list. I would expect the entire list to be displayed (as described in the documentation for min-length="0")
2. Trying to delete all characters in the field results in the first item being selected. This behaviour means that you cannot choose anything other than the first item at all, without some very awkward workarounds (typing your selection after the first character, then going to the beginning of the field, and forward-deleting the first character - not practical)
3. Trying to clear the field's value results in the behaviour described in (2)

**Comment by ghiden** [comment]
I personally never liked auto-match feature. But I'll have a look. Thanks for reporting.

**Comment by antony** [comment]
auto-match is essential for writing clean functional tests (without protractor). Otherwise you have to screw around with your framework trying to click items in a list which may or may not be populated. With auto-match you can simply fill in input fields as you would a regular input.

In the same vein, it's essential for people copy-pasting values into fields. You don't want to have to click a list item after the paste.

I think the resolution to the problem described above is simply to not auto-match on an empty string value, because it seems to match everything, or nothing. I can't figure out which.

Doesn't explain (1.) though. That one I can't figure out.
