### ISSUE TITLE
Special character doesn't matches

### ISSUE THREAD

**Issue by fatih-bayar** [ghiden/angucomplete-alt#164]
For example: I have "İstanbul" value in my list and i'm typing "istanbul" with lower "i", but it's doesn't matches with the "İstanbul". I guess there is a problem with Turkish "I, İ, ı, İ" characters.

**Comment by ghiden** [comment]
The current string comparison is quite primitive.
Just an idea but maybe I should expose the comparison function so that user can implement your own function.

**Comment by thiphariel** [comment]
Any plan on this enhancement ? It's really a needed feature for French addresses, many road name contains "éèà..." 
 Thanks

**Comment by jrbecart** [comment]
@thiphariel  Thanks it works.

There is a typo in your file:

Replace this (line 534): 

```javascript
// Remove diacritics on value & str
value = removeDiacritics(value);
str = removeDiacritics(value);
```

by this:

```javascript
// Remove diacritics on value & str
value = removeDiacritics(value);
str = removeDiacritics(str);
```

**Comment by rafwell** [comment]
+1 for brazilian people, please :)

**Comment by ghiden** [comment]
For cases like this, please use custom search.
https://github.com/ghiden/angucomplete-alt#using-local-data-with-custom-search-function
