### ISSUE TITLE
field-required

### ISSUE THREAD

**Issue by ilanCambium** [ghiden/angucomplete-alt#165]
Hi there,
I am trying to use your great plugin inside a form. The input is required. I want that on submit the field will change it border-color. I cant use the field-required-class.

Thanks.
ilan

**Comment by ghiden** [comment]
Can you provide a jsbin or plankr example?

**Comment by ilanCambium** [comment]
Hi.
I created this: http://plnkr.co/edit/PU3jZn?p=preview
As you can see the text field get the "has-error" class with the angular-validator.js.
I want that your plugin will behave the same. How can i do it?

Thanks,
Ilan

**Comment by ghiden** [comment]
Thanks. I'll have a look.

**Comment by ghiden** [comment]
angular-validator requires 2-way data binding but angucomplete-alt does not provide 2-way data binding. So it doesn't work. Sorry.
