### ISSUE TITLE
Allow remote-url-request-formatter to return the full config object

### ISSUE THREAD

**Issue by wiceywkus** [ghiden/angucomplete-alt#166]
Instead of this:
         if (scope.remoteUrlRequestFormatter) {
            params = {params: scope.remoteUrlRequestFormatter(str)};
            url = scope.remoteUrl;
          }

Do this:
         if (scope.remoteUrlRequestFormatter) {
            params = scope.remoteUrlRequestFormatter(str);
            url = scope.remoteUrl;
          }

this allows the request formatter to add request header.

functions would have to return at least the params and the headers part of the config object:

var config = { params : {{params}}, headers : {{headers}} };
return config;

**Comment by ghiden** [comment]
Thanks for your suggestion. I should have done this in the first place but now I can't do this as it will break the current implementation.
I suppose #128 would help. Then you can do whatever you want.
