### ISSUE TITLE
Interpolation Providers Hard Coded

### ISSUE THREAD

**Issue by egekhter** [ghiden/angucomplete-alt#168]
I've setup my app with 
app.config(['$interpolateProvider', function($interpolateProvider) {
    $interpolateProvider.startSymbol('<%');
    $interpolateProvider.endSymbol('%>');
}]);

Just a heads up that in this case you should find/replace all occurrences of {{ and }} in this module.

**Comment by ghiden** [comment]
It's supported now. The directive should pick up the change automatically.
