### ISSUE TITLE
Angucomplete-alt doesn't work with custom angularjs tag?

### ISSUE THREAD

**Issue by manhthang2504** [ghiden/angucomplete-alt#170]
I have changed standard angular tag from { } to <% %>.

When using angucomplete-alt, I have used the code in usage guide:

<angucomplete-alt id="ex1"
              placeholder="Search countries"
              pause="100"
              selected-object="selectedCountry"
              local-data="countries"
              search-fields="name"
              title-field="name"
              minlength="1"
              input-class="form-control form-control-small"/>

but it doesn't display properly. It just display an un-style input field (instead of Bootstrap-formatted field), with following code display next on the face of the web:

ng-class="{'angucomplete-input-not-empty': notEmpty}" ng-model="searchStr" ng-disabled="disableInput" type="" placeholder="Search countries" maxlength="524288" ng-focus="onFocusHandler()" class="form-control form-control-small" ng-focus="resetHideResults()" ng-blur="hideResults($event)" autocapitalize="off" autocorrect="off" autocomplete="off" ng-change="inputChangeHandler(searchStr)"/> 

I checked the rendered html

<angucomplete-alt id="ex1" class="ng-isolate-scope" input-class="form-control form-control-small" minlength="1" title-field="name" search-fields="name" local-data="countries" selected-object="selectedCountry" pause="100" placeholder="Search countries">
<div class="angucomplete-holder ng-binding" ng-class="{'angucomplete-dropdown-visible': showDropdown}">
<input id="ex1_value" name="<%inputName%">
ng-class="{'angucomplete-input-not-empty': notEmpty}" ng-model="searchStr" ng-disabled="disableInput" type="" placeholder="Search countries" maxlength="524288" ng-focus="onFocusHandler()" class="form-control form-control-small" ng-focus="resetHideResults()" ng-blur="hideResults($event)" autocapitalize="off" autocorrect="off" autocomplete="off" ng-change="inputChangeHandler(searchStr)"/>
<div id="ex1_dropdown" class="angucomplete-dropdown ng-hide" ng-show="showDropdown">
<div class="angucomplete-searching ng-binding ng-hide" ng-bind="textSearching" ng-show="searching">Searching...</div>
<div class="angucomplete-searching ng-binding" ng-bind="textNoResults" ng-show="!searching && (!results || results.length == 0)">No results found</div>
</div>
</div>
</angucomplete-alt>

I think it doesn't work properly must relate to the brace { letter (but not sure).

Please help me. Thank you.

**Comment by Boshen** [comment]
If you have changed the default `{{ }}` style ... then you have to provide your own template

**Comment by manhthang2504** [comment]
Thank you very much.

**Comment by manhthang2504** [comment]
It works, however, there're 2 problems incurred:
- It disable all other input fields.
- The matched results does not highlight typed character (in example, it's red highlighted).

My revised template:
<script type="text/ng-template" id="/my-custom-template.html">
             	<div class="angucomplete-holder" ng-class="{'angucomplete-dropdown-visible': showDropdown}">
             		<p>This is custom</p>
             		<input ng-model="searchStr"
             		ng-disabled="disableInput"
             		type="text"
             		placeholder="<%placeholder%>"
             		ng-focus="onFocusHandler()"
             		class="<%inputClass%>"
             		ng-focus="resetHideResults()"
             		ng-blur="hideResults($event)"
             		autocapitalize="off"
             		autocorrect="off"
             		autocomplete="off"
             		ng-change="inputChangeHandler(searchStr)"/>
             		<div class="angucomplete-dropdown" ng-show="showDropdown">
             			<div class="angucomplete-searching" ng-show="searching" ng-bind="textSearching"></div>
             			<div class="angucomplete-searching" ng-show="!searching && (!results || results.length == 0)" ng-bind="textNoResults"></div>
             			<div class="angucomplete-row" ng-repeat="result in results" ng-click="selectResult(result)" ng-mouseenter="hoverRow($index)" ng-class="{'angucomplete-selected-row': $index == currentIndex}">
             				<div ng-if="imageField" class="angucomplete-image-holder">
             					<img ng-if="result.image && result.image != ''" ng-src="<%result.image%>" class="angucomplete-image"/>
             					<div ng-if="!result.image && result.image != ''" class="angucomplete-image-default"></div>
             				</div>
             				<div class="angucomplete-title" ng-if="matchClass" ng-bind-html="result.title"></div>
             				<div class="angucomplete-title" ng-if="!matchClass"><% result.title %></div>
             				<div ng-if="matchClass && result.description && result.description != ''" class="angucomplete-description" ng-bind-html="result.description"></div>
             				<div ng-if="!matchClass && result.description && result.description != ''" class="angucomplete-description"><%result.description%></div>
             			</div>
             			<div class="angucomplete-row" ng-click="selectResult({title: searchStr, originalObject: { name: searchStr, custom: true } })" ng-mouseenter="hoverRow(results.length)" ng-class="{'angucomplete-selected-row': results.length == currentIndex}">
             				<div class="angucomplete-title">Select custom country '<% searchStr %>'</div>
             			</div>
             		</div>
             	</div>
             </script>
