### ISSUE TITLE
Required border is missing when clearing hidden autocomplete

### ISSUE THREAD

**Issue by macgyver76** [ghiden/angucomplete-alt#171]
Something's wrong with clearing autocomplete while required is set to true. Here's a [plunk](http://plnkr.co/edit/TpnbsQW7D7dXLAMOClrN?p=preview). 

Plunk usage info: 
1. Select *aaa* from autocomplete 
2. Click *hide* button
3. Click *show* button
4. Border color around autocomplete input is not present

Any ideas?

**Comment by ghiden** [comment]
Thank you for reporting. I verified it. It's a bug.
Hopefully I can release a fix tomorrow.
