### ISSUE TITLE
Feature request: input-changed should accept function call rather then function reference

### ISSUE THREAD

**Issue by kub1x** [ghiden/angucomplete-alt#172]
When I have following code, I'd like to have a way to call the callback along with it's value. On regular input I use the [ng-change](https://docs.angularjs.org/api/ng/directive/ngChange#!) for it. It would be really neat if input-changed worked the same way. Currently I don't see a way to do it, so please let me know if I'm missing something. 

```html
<div ng-repeat="user in users">
  <angucomplete-alt input-changed="changedInputForUser(user)" />
</div>
```

Thanks

**Comment by ghiden** [comment]
Try this:
```js
$scope.changedInputForUser = function(str) {
  var user = $scope.users[this.$parent.$index]
  // do something with user and str
}
```

**Comment by antony** [comment]
This should definitely be documented. I'll do it.

**Comment by ghiden** [comment]
Thank you @antony
