### ISSUE TITLE
Autocomplete OR Insert

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [ghiden/angucomplete-alt#176]
Is it possible to use this as an autocomplete but, if there is no match, to insert a new value? I use a scope variable as the "selected-object" attribute but, the variable is not bound if there is no match...

Thanks!

**Comment by ghiden** [comment]
Have you tried override-suggestions? http://ghiden.github.io/angucomplete-alt/#example4

**Comment by DanielFerreiraJorge** [comment]
Thank you very much... It worked... Im closing this...
