### ISSUE TITLE
Predefined selectedObject

### ISSUE THREAD

**Issue by jsonmurphy** [ghiden/angucomplete-alt#18]
Hi, I'd like to know if it's possible to have the selectedObject predefined. For instance, when an object is loaded from a remote server. I've tried:

*    setting override-suggestions="true";
*    retaining the format of `{"title":.., "description":..,"image":.., "originalObject":... }` on the server side.

**Comment by DavidePastore** [comment]
:+1:

**Comment by ghiden** [comment]
Use initial-value with object.

**Comment by AlcheTse** [comment]
my way to solve ng-model binding:

add "searchStr: '=ngModel' in the directive's internal scope, like:

return {
      restrict: 'EA',
      require: '^?form',
      scope: {
        selectedObject: '=',
        disableInput: '=',
        ......
        inputName: '@',
        searchStr: '=ngModel'
      }
      ......
}

that can be use ng-Model as input element in form.
