### ISSUE TITLE
Should clearing input's searchStr and tabbing away remove scope.selectedObject?

### ISSUE THREAD

**Issue by davidmgarrett** [ghiden/angucomplete-alt#182]
I fixed it by calling callOrAssign(undefined) in the hideTimer
  
```javascript
      scope.hideResults = function(event) {
          if (mousedownOn && mousedownOn.indexOf('angucomplete') >= 0) {
            mousedownOn = null;
          }
          else {
            hideTimer = $timeout(function() {
              clearResults();
              scope.$apply(function() {
                if (scope.searchStr && scope.searchStr.length > 0) {
                  inputField.val(scope.searchStr);
                }
                //new: clear selectedObject
                else {
                  callOrAssign(undefined);
                }
              });
            }, BLUR_TIMEOUT);
```

**Comment by ghiden** [comment]
Could you describe the exact step that user would take?
Is it about receiving angucomplete-alt:clearInput event then hitting tab?

**Comment by davidmgarrett** [comment]
Thanks for following up, Nozaki.

Originally, I was trying to keep my model and autocomplete display in sync.
If I selected an item in the autocomplete, the model would update and they would match.
However, if I cleared the autocomplete, the model would not update to “undefined” yet the autocomplete would be blank.

I decided to change my UI to always clear the value in the autocomplete after selection.
   angucomplete-alt( …  clear-selected="true"  …)

                -David

**Comment by davidmgarrett** [comment]
Thanks for making this change.

I’m trying to use angucomplete-alt like a typical dropdown control, but with filtering.

Is there an easy way for the selected-object.originalObject to two-way bind to a property on my model?
If model.state changes, I’d like the angucomplete input to show the corresponding state as well.

Model: { states: [‘Georgia’,…], state: ‘Georgia’ }

                angucomplete-alt(
                                placeholder="Choose State…”
                                selected-object="model.state"
                                local-data="model.states"
                                search-fields="?"
                                title-field="?"
                                minlength="0"
                                input-class="form-control form-control-small"
                                class="ng-isolate-scope")



[http://cdn8view1.turner.com/tbs/tbscomm/emailgraphics/logosig_mss.png]
________________________________
DAVID GARRETT | APPLICATIONS ARCHITECT | MEDIA SOFTWARE & SERVICES
O. 404-575-6310 | C. 404-583-1970 | DAVID.GARRETT@TURNER.COM<mailto:DAVID.GARRETT@TURNER.COM>
TURNER BROADCASTING SYSTEM, INC. | 1000 TECHWOOD DRIVE NW ATLANTA, GA 30318

**Comment by ghiden** [comment]
Hi David,

Angucomplete-alt does not provide 2-way data binding. This behavior is from the original Angucomplete. The closest you can do is use initial-value. Have a look at the example 9 http://ghiden.github.io/angucomplete-alt/#example9
