### ISSUE TITLE
Why am i not getting a scrollable Dropdown?

### ISSUE THREAD

**Issue by sfaizan** [ghiden/angucomplete-alt#187]
This is how it looks like
![image](https://cloud.githubusercontent.com/assets/9317338/8406574/4f6f7244-1e7b-11e5-8312-9d568f0bf76e.png)

and the code for it i have written is :(its in Jade):
angucomplete-alt#sectors(placeholder='Search sectors', local-data='sectors1', selected-object='onSector1Selected', search-fields='Sector', pause='300', minlength='1', title-field='Sector',input-class="form-control form-control-small")

**Comment by MalloryEaton** [comment]
See this page:
https://github.com/ghiden/angucomplete-alt

![image](https://cloud.githubusercontent.com/assets/10622107/8408741/36e65e10-1e38-11e5-9714-38a2267cf05e.png)

**Comment by ghiden** [comment]
@MalloryEaton Thank you for following up.

**Comment by sfaizan** [comment]
Thanks for the reply, will try it out
