### ISSUE TITLE
Set focus on angucomplete-alt input on page load.

### ISSUE THREAD

**Issue by dkromp** [ghiden/angucomplete-alt#188]
What's the best way of setting the focus to the angucomplete-alt input on page load?

**Comment by dkromp** [comment]
The solution, as found in other folk's issues appears to be:
```
$timeout(function() {
      var searchInput = document.getElementById('searchField_value');
      searchInput.focus();
	}, 0);
```

**Comment by ghiden** [comment]
The easiest is to use custom template.
Have a look at this solution.
https://github.com/ghiden/angucomplete-alt/issues/175
