### ISSUE TITLE
Append closing characters to end of search string for remote-url?

### ISSUE THREAD

**Issue by pchipel1** [ghiden/angucomplete-alt#189]
Need to append closing quote and parenthesis after searchString for OData syntax like this:
http://localhost:58177/breeze/breeze/loginnums/?$filter=startswith(LoginNum1,'searchString')
or like this:
http://localhost:58177/breeze/breeze/loginnums/?$filter=startswith(LoginNum1,%27searchString%27)

Is this possible?  Tried using the remote-url-request-formatter but that appears to be set up for key value pairs for query parameters rather than a situation like this.  

Thanks for your help.

**Comment by ghiden** [comment]
Have a look at remote-api-handler
https://github.com/ghiden/angucomplete-alt#remote-api-handler

**Comment by pchipel1** [comment]
Awesome!  Thanks for pointing to the solution.
