### ISSUE TITLE
Match class selects title and description when search filed is set only to title.

### ISSUE THREAD

**Issue by aleks83** [ghiden/angucomplete-alt#190]
I would like to search only by title and use match-class to highlight but description field get also highlighted.
Code from precessResults function:
 if (scope.matchClass) {
                formattedText = findMatchString(text, str);
                formattedDesc = findMatchString(description, str);
 }

Solution would be to check search fields there:
if (scope.matchClass) {
                  for (s = 0; s < searchFields.length; s++) {
                      if (searchFields[s] === scope.titleField)
                          formattedText = findMatchString(text, str);
                      if (searchFields[s] === scope.descriptionField)
                          formattedDesc = findMatchString(description, str);
                  }
              }

**Comment by ghiden** [comment]
I guess the easiest solution would be to change your css like this
.angucomplete-description .highlight {
	color: #000; // your default text color
}
