### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by tomchiverton** [ghiden/angucomplete-alt#191]

**Comment by tomchiverton** [comment]
Certainly it will need
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Polyfill
adding to the caller as well.

**Comment by ghiden** [comment]
Thanks for reporting. I thought I was careful not to use forEach but when one of pull requests had forEach in it.

**Comment by tomchiverton** [comment]
It also needs a poly fill for getComputedStyle, such as 
http://snipplr.com/view/13523/
