### ISSUE TITLE
field-required broken

### ISSUE THREAD

**Issue by fmccown** [ghiden/angucomplete-alt#192]
I've [created a Plunker](http://plnkr.co/edit/W3SOPYHkJsXcovnCdrDT?p=preview) to demonstrate the current problem with the field-required attribute. Note that both search boxes are marked as required.  However, the $valid attribute remains "true" no matter if something is selected or not.  

Also the form's $valid and $invalid is set according to the last state of the angucomplete box that was last accessed.  So if you select a country the form becomes valid even though no sport was selected.  Or you can select a sport after removing the country selection and see the form is valid.  I believe this problem is due to the call `ctrl.$setValidity` which sets the form's validity instead of the control's validity.

**Comment by ghiden** [comment]
Actually this is working, but not as you think. The way this is implemented is setting the form controller's validity. At the time of this implementation I believe it was about a year ago, there wasn't any way to add an input field dynamically to a form controller. I'm not sure if it is still possible or not.
So, to make your example work, you need to provide field-required-class for each directive.
http://plnkr.co/edit/aeB28M?p=preview
Then each directive sets its own class name to the form controller. Then the form controller takes care of all form elements being invalid or not.

**Comment by fmccown** [comment]
Ah, I see what you are doing.  So by providing a field-required-class="className" on the directive, the class "ng-invalid-className" gets added to the form's class attribute which makes the form invalid.  Thanks for the clarification.

**Comment by ghiden** [comment]
Ideally, this directive should be added to the form controller but currently it's not how it is implemented. I just created a ticket to look into this #196.
