### ISSUE TITLE
Input control's title can not be changed by updating the bound selected-object

### ISSUE THREAD

**Issue by tomchiverton** [ghiden/angucomplete-alt#193]
My template has 
		selected-object="selectedPerson"
but when the controller does
			$scope.selectedPerson.title = '';
or even
			$scope.selectedPerson = {};
the title is not cleared in the input control.
If the view dumps out selected person:
    {{ selectedPerson | json }}
then the title can be seen to change there, but not in the component

**Comment by ghiden** [comment]
selected-object is not 2-way bound variable. So, you can't change it from your controller.
It is only set from the directive, it's only one-way.
It's been designed like this from the original angucomplete.
I haven't changed this internal structure.
If you want to set its initial value, then you need to use initial-value.
Have a look at this example. http://ghiden.github.io/angucomplete-alt/#example9

**Comment by tomchiverton** [comment]
I don't want to set an initial value, but rather clear (or change) the displayed title when something else happens elsewhere e.g. an 'add' button is pressed.

**Comment by ghiden** [comment]
Just use this broadcast.
https://github.com/ghiden/angucomplete-alt#clear-input

**Comment by pavan496** [comment]
Clearing the value is working well. How do I set a different value to the control?

**Comment by ghiden** [comment]
@pavan496  You mean after clearing the value? Just use the input field again.

**Comment by tomchiverton** [comment]
I think he meant from code, not user interaction.

**Comment by ghiden** [comment]
Oh, ok. If that's the case, there is no way setting a value from controller.

**Comment by pavan496** [comment]
Okay.  Thanks..

**Comment by tomchiverton** [comment]
Seems the right way to add this would be to broadcast an event containing the new selected object ?

**Comment by artvlasov** [comment]
I have a similar problem.
In my case, there is a set of object, one of this set is choosen by some selector control. Selected object is editable and is bound to form by a number of ng-model. One of these fields is editable with help of angucomplete-alt. I do really need to programmaticaly set selected-object, or initial-value, or broadcast something to set value of underlying text input.
I see ```unbindInitialValue``` is called to remove watcher from initial value. Simple dirty solution is to remove this call. But I really don't want to use monkey-patched version of your control.

**Comment by ghiden** [comment]
This directive does not support 2-way binding so it's not possible to update the input value programmatically. Not removing the watcher might solve your issue. But I'm not planning to change this behavior. If I really have to implement it, then I would probably use event system.

**Comment by artvlasov** [comment]
If you want to keep your course and don't want to break existing code and behaviour, you have to add event handlers and listen appropriate messages. It might be not too convenient, but I see no other alternative.
I think, many users would appreciate this feature. I could help you, because I need to fix it in my project as soon as possible.

**Comment by tomchiverton** [comment]
@artvlasov go ahead and submit a patch that listens to some new event. I'm bound to need it at some point too, just hadn't had a chance to do it in advance yet.
