### ISSUE TITLE
Add directive to form controller dynamically

### ISSUE THREAD

**Issue by ghiden** [ghiden/angucomplete-alt#196]
Currently field-required is implemented using form controller's $setValidity rather than the directive's input element's $setValidity. When it was implemented, it was impossible to add a new input field to form controller dynamically. Maybe it is possible now? This is related with #192.

**Comment by fmccown** [comment]
I wanted to set the validity on the `<input>` field, so I specified `<div angucomplete-alt input-name="myInput">` and then added this to `handleRequired`:

```javascript
if (scope.inputName) {
   ctrl[scope.inputName].$setValidity(requiredClassName, valid);
}
```

**Comment by ghiden** [comment]
Thanks. I'll have a look.

**Comment by Abegade** [comment]
I modified angucomplete-alt directive and added ng-required to be consistent with the rest of my input fields and i wrote a directive to handle this situation. 

It works with this basic setup (i did not try it with the full set of angucomplete options tho):

```
<div angucomplete-alt id="test_id"
	      angucomplete-bind-to-form-controller
	      input-name="test_name"
	      ng-required="test.required"
          placeholder="Start writing"
          text-no-results="No results found"
          text-searching="false"
          minlength="2"
          remote-url-response-formatter="formatTestResponse"
          remote-url="/fs/test/test.page?query="
          selected-object="bindTest"
          title-field="testField" />
```
and the directive is:

```javascript
testDirectives.directive('angucompleteBindToFormController', function() {
  return {
    restrict: "A",
    require: '^form',
    replace: false,
    link: function(scope, elem, attr, form) {
      var formName = form.$name;
      var inputName = attr.inputName;
      scope[formName][inputName] = scope[formName]['{{inputName}}'];
      scope[formName][inputName].$name = elem.attr('name');
      delete(scope[formName]['{{inputName}}']);
    }
  };
});
```
This works for multiple directives inside the same form as well, the basic idea is to swap the wrong field binded in the form controller (the one called {{inputName}}) with one which references the correct name of the input field. The form controller does the rest like expected.

The only doubt i still have is about any unwanted side-effect this could bring.

**Comment by ghiden** [comment]
Released v2.0.0

**Comment by whisher** [comment]
Hi ghiden, 
sorry to bother you but field-required doesn't work yet :(

**Comment by ghiden** [comment]
@whisher just saying "it doesn't work" does not help me much.
What is not working? 
What errors are you getting?
Can you create a jsbin or plnkr example?

**Comment by whisher** [comment]
Thanks for the quick reply.
@ghiden you agree but the simple problem
is if I put it in an angular form the form is validated
even if the input is empty and I've got no any error
in the console
like this:
```javascript
<div angucomplete-alt
              id="searchAutocomplete"
              placeholder="Search countries"
              maxlength="50"
              pause="100"
              selected-object="vm.place"
              local-data="vm.places"
              search-fields="name"
              title-field="name"
              minlength="1"
              input-class="form-control form-control-small"
              match-class="highlight"
              field-required="true">
            </div>
```

**Comment by ghiden** [comment]
You are missing "input-name".

**Comment by whisher** [comment]
@ghiden thanks just a lot it works fine :)
