### ISSUE TITLE
Problem understanding (and using) the two-way-bound data of "selected-object" attribute

### ISSUE THREAD

**Issue by mdentinho** [ghiden/angucomplete-alt#197]
Hello there,

I've been trying to understand how the `selected-object` attribute works. In the README it says:
>
Either an object in your scope or callback function.
If you set an object, **it will be two-way-bound data as usual**.
If you set a callback, it gets called when selection is made. 

As far as I understand, `two-way-bound data` or `Two-Way Data Binding` ([as AngularJs' Docs call it](https://docs.angularjs.org/guide/databinding)) is:
> 
1. Changes to **View** updates **Model**
2. Changes to **Model** updates **View**

The first definition works just fine: After selecting an item from the suggestions list in the **View**, the object set in the `selected-object` is updated.

The second definition doesn't seems to work. After setting/changing the`selected-object` object's content, the **View** doesn't change.

After looking a lot for solutions on this, I found a conflicting information in the issue #82, where @ghiden says:
>
From the original angucomplete and even this -alt, you can't 2-way bind.
It's design makes really difficult to do 2-way bind.

- There's also a similar situation in the issues #108 and #143.

I have also found a few issues that point to `initial-value` as a solution for similar (but not equal) cases. But this solution is just a `One-Way Data Binding` and cannot update the **View** if the object set to this attribute is updated after it's set for the first time.

So, it seems that it's just a wrong information in the README, but it would be good to confirm that.

In any case, I can see a few use cases that this would be necessary:
* Dependent input fields (i.e.: A zip code input field that sets another angucomplete-alt's input fields, like state or city, contents)
* Common options highlighted suggestions (i.e.: A toggle buttons group with the most common items that users use to select from the suggestions list. Instead of searching for an item in the angucomplete-alt's input field, the user will just click one of the buttons and the field would be automatically filled)

I know that it has been said that "It's [this component] design makes really difficult to do 2-way bind.", but as UX Design today is saying that typing with suggestions is better than select menus for long list of options, this may be something to start to think about. 

Also, please let me know if I can help with something or maybe if I can find the solution in another place. ;)

Cheers!

**Comment by ghiden** [comment]
Sorry for the confusion. I'll update the README. No wonder people keep asking me why 2-way data binding isn't working.

**Comment by nixoschu** [comment]
Hey,

i was just reading this, while searching for some answers for the data binding. So I'm just asking my question here.

If 2-way binding isn't working, there is no way one could reset the 'selectedObject' from the controllers scope right ?

**Comment by ghiden** [comment]
@nixoschu That's right. It's only one way from directive to controller.

**Comment by mdentinho** [comment]
I'm closing the issue, since the README has been updated and there's no plans to make it work in other way. Thanks.
