### ISSUE TITLE
Dropdownlist pops-up while navigating using tab.

### ISSUE THREAD

**Issue by shashykant** [ghiden/angucomplete-alt#199]
goto http://ghiden.github.io/angucomplete-alt/#example2

enter 'a', and selected any suggested value.
goto example#1. press tab.
notice the dropdown appears. This should not appear as value is already selected and changes are not being made.

we need to modify the code from
![image](https://cloud.githubusercontent.com/assets/12561115/8540581/9f059610-24a4-11e5-9b76-ae3d3e6d7bf6.png)

to 

![image](https://cloud.githubusercontent.com/assets/12561115/8540596/b55fd5b0-24a4-11e5-8423-da4f08411fdc.png)

to skip tab.

and need to modify the code in getlocalresults fn as it dosent work with dataset with numeric data.

please modify as
![image](https://cloud.githubusercontent.com/assets/12561115/8540622/0ba68428-24a5-11e5-9341-9c4c7c156b45.png)

**Comment by ghiden** [comment]
This behaves same as twitter typeahead. So I won't fix it.
But the numeric value handling, I think now it's time to add. We have this very old issue #47.
