### ISSUE TITLE
Autocomplete suggestions not aligned with input field.

### ISSUE THREAD

**Issue by sweisman** [ghiden/angucomplete-alt#202]
I am trying to use this Bootstrap (2.x I believe). I have a row like this:

    <div class="row-fluid">
        <span class="span3"><strong>Room</strong></span>
        <angucomplete-alt
            pause="100"
            selected-object="data.room"
            initial-value="data.room"
            local-data="room_options"
            search-fields="name"
            title-field="name"
            minlength="1"
            input-name="room"
            input-class="inp-form span9" />
    </div>

According to Chrome dev tools, the DOM is:

    <div class="row-fluid">
        <span class="span3"><strong>Room</strong></span>
        <angucomplete-alt
            pause="100"
            selected-object="data.room"
            initial-value="data.room"
            local-data="room_options"
            search-fields="name"
            title-field="name" minlength="1"
            input-name="room"
            input-class="inp-form span9"
            class="ng-isolate-scope">
            <div class="angucomplete-holder" ng-class="{'angucomplete-dropdown-visible': showDropdown}">
                <input id="_value" name="room" ng-class="{'angucomplete-input-not-empty': notEmpty}"
                    ng-model="searchStr" ng-disabled="disableInput" type="{{inputType}}" placeholder=""
                    maxlength="524288"
                    ng-focus="onFocusHandler()"
                    class="inp-form span9 ng-valid-maxlength angucomplete-input-not-empty ng-touched"
                    ng-blur="hideResults($event)" autocapitalize="off" autocorrect="off" autocomplete="off" ng-change="inputChangeHandler(searchStr)"> 
                <div id="_dropdown" class="angucomplete-dropdown ng-hide" ng-show="showDropdown">
                    <div class="angucomplete-searching ng-binding ng-hide" ng-show="searching" ng-bind="textSearching">Searching...</div>
                    <div class="angucomplete-searching ng-binding" ng-show="!searching &amp;&amp; (!results || results.length == 0)" ng-bind="textNoResults">No results found</div>
                    
                </div>
            </div>
        </angucomplete-alt>
    </div>

The &lt;angucomplete-alt&gt; tags work, and the suggestions pop up. The problem is, they pop up all the way at the left of the outer &lt;div class="row-fluid"&gt;, instead of just below &lt;angucomplete-alt&gt; as expected. Is there some CSS tweaks I can apply to fix this?

**Comment by ghiden** [comment]
The css that comes with this directive is just an example.
You have to to modify it to suit your design.
If you can create a plnkr example or something, I can have a look.

**Comment by ikb42** [comment]
I have a similar problem.
The dropdown appears at the top of the form, over all the prior fields.

The form I have is (jade):
````
form 
    div
        input(xxX)
        input(xxX)
        div(angucomplete-alt...)
````

**Comment by ghiden** [comment]
This is not an issue with this directive.
Please adjust your css.

**Comment by dcmorse** [comment]
Here's how to adjust the CSS:

```

.angucomplete-dropdown { 
  top: 32px;
  left: 25%; /* compute the left side of the angucomplete-alt element here, for me it was 25% */
}
```
