### ISSUE TITLE
IE8 Compatibility

### ISSUE THREAD

**Issue by brianmfalls** [ghiden/angucomplete-alt#204]
Doesn't appear that angucomplete-alt is compatible with IE8 at all.  I know, IE8 sucks, but many of us still have to support the darn thing.

**Comment by ghiden** [comment]
There is a way to run it.
1. You have to use angular 1.2.28. Angular does not support IE8 anymore. So you have to downgrade it.
2. Only part that fails in angucomplete-alt is the part that uses promises.
Change this code into the following:
```js
scope.remoteApiHandler(str, httpCanceller.promise)
  .then(httpSuccessCallbackGen(str))
  .catch(httpErrorCallback);
```

```js
/* IE8 compatible */
scope.remoteApiHandler(str, httpCanceller.promise)
  ['then'](httpSuccessCallbackGen(str))
  ['catch'](httpErrorCallback);
```

**Comment by brianmfalls** [comment]
Sweet.  We are on 1.2.28.  I'll try changing that bit of code.  Thanks!!!

**Comment by tomchiverton** [comment]
See also #191
