### ISSUE TITLE
SyntaxError: expected expression, got '.'

### ISSUE THREAD

**Issue by brianmfalls** [ghiden/angucomplete-alt#205]
I unzipped angucomplete-alt and moved all of the files into a sandbox directory to 'play around' with it in hopes of eventually integrating it into a single page application. Unfortunately, I get the error listed in the title: SyntaxError: expected expression, got '.'

I haven't tweaked anything in the code. Is there some configuration that needs to happen in order for the index.html in the example directory to work without this error?

The full error is listed below.

Error: [$injector:modulerr] http://errors.angularjs.org/1.4.0/$injector/modulerr?p0=app&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.0%2F%24injector%2Fmodulerr%3Fp0%3Dangucomplete-alt%26p1%3D%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.4.0%252F%2524injector%252Fnomod%253Fp0%253Dangucomplete-alt%250AF%252F%253C%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A6%253A416%250Ace%252F%253C%252F%253C%252F%253C%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A23%253A384%250Aa%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A23%253A25%250Ace%252F%253C%252F%253C%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A23%253A1%250Ag%252F%253C%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A37%253A202%250An%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A7%253A320%250Ag%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A37%253A50%250Ag%252F%253C%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A37%253A219%250An%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A7%253A320%250Ag%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A37%253A50%250Abb%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A40%253A332%250Azc%252Fd%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A19%253A264%250Azc%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A20%253A62%250AYd%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A18%253A389%250A%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A288%253A160%250Aa%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A175%253A4%250AGf%252Fc%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.4.0%252Fangular.min.js%253A35%253A46%250A%0AF%2F%3C%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A6%3A416%0Ag%2F%3C%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A37%3A476%0An%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A7%3A320%0Ag%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A37%3A50%0Ag%2F%3C%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A37%3A219%0An%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A7%3A320%0Ag%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A37%3A50%0Abb%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A40%3A332%0Azc%2Fd%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A19%3A264%0Azc%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A20%3A62%0AYd%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A18%3A389%0A%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A288%3A160%0Aa%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A175%3A4%0AGf%2Fc%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0%2Fangular.min.js%3A35%3A46%0A

**Comment by ghiden** [comment]
That's a typical angular error with no clue.
The example directory should work without changing anything.

**Comment by brianmfalls** [comment]
I think it should too.  ;)  However, that is the error I get.  Pretty discouraging to say the least.

**Comment by ghiden** [comment]
What's your environment?

**Comment by brianmfalls** [comment]
Windows 7 Enterprise
Apache 2
Tried it it IE, FF, and Chrome.

LMK if you need more specifics.  "Environment" is a big paintbrush.  ;)

**Comment by ghiden** [comment]
Try hitting the index.html in example folder from file explorer.
It should work without hosting it on Apache.

**Comment by ghiden** [comment]
I'm closing this as no one else is complaining this. Please re-open it if you need more help.
