### ISSUE TITLE
Empty dropdown in case of no results found

### ISSUE THREAD

**Issue by miteshkamat27** [ghiden/angucomplete-alt#209]
I am using angucomplete-alt, it shows no results found text when no matching results are found in all the browsers except safari. In safari it shows an empty dropdown.
Can anyone help me on this?

<img width="385" alt="screen shot 2015-07-14 at 7 18 57 pm" src="https://cloud.githubusercontent.com/assets/13333500/8674697/3d0c51ce-2a5d-11e5-9936-01cd7b839496.png">

**Comment by ghiden** [comment]
It works fine on my safari.

**Comment by miteshkamat27** [comment]
Can you tell me what would be the reason?

**Comment by ghiden** [comment]
Can you create a jsbin or plunkr example? I can't really help if I can't reproduce it.

**Comment by shashykant** [comment]
Mitesh,
I Guess u are testing with "Safari on Windows".
Please test "Safari on Mac".

**Comment by ghiden** [comment]
I'm closing this as no one else is complaining this. Please re-open it if you need more help.
