### ISSUE TITLE
angucomplete-alt dropdown doesnot disappear on clicking outside.

### ISSUE THREAD

**Issue by miteshkamat27** [ghiden/angucomplete-alt#210]
I enter any keyword which has results in angucomplete-alt , so it shows results as expected.
But when I click somewhere outside the dropdown, the dropdown doesnot close/ disappear.
Can anyone suggest me a solution for this.

Thanks,
Mitesh

**Comment by ghiden** [comment]
Which browser is it?

**Comment by miteshkamat27** [comment]
Its happening in chrome, IE, firefox

**Comment by shashykant** [comment]
Mitesh are you trying to refer to https://github.com/ghiden/angucomplete-alt/issues/194.
It is resolved.

**Comment by miteshkamat27** [comment]
Thanks shashy!!!

**Comment by miteshkamat27** [comment]
@shashykant  @ghiden : It worked earlier, but now the issue still persists. I added the changes from angucomplete-alt.js in my file but its not working. The dropdown is not closing on clicking outside.

**Comment by miteshkamat27** [comment]
The dropdown fix that u added doesnot hide results.

**Comment by ghiden** [comment]
Are you using angucomplete or angucomplete-alt?

**Comment by shashykant** [comment]
i m using angucomplete-alt. its recommended to use -alt.

**Comment by miteshkamat27** [comment]
Even m using angucomplete-alt

**Comment by ghiden** [comment]
Tell me which version works and which doesn't.
What OS and browsers are you are using?

**Comment by shashykant** [comment]
can u try this first
https://github.com/ghiden/angucomplete-alt/issues/194
and see if it works here.

Hope you have not modified ur angucomplete-alt.
I m using latest chrome. which browser ver u r using?

**Comment by miteshkamat27** [comment]
I modified the js file as mentioned in the raw code .
I am using latest chrome Version 44.0.2403.107 m

**Comment by shashykant** [comment]
can u paste ur code here

**Comment by ghiden** [comment]
I'm closing this as no one else is complaining this. Please re-open it if you need more help.
