### ISSUE TITLE
Ability to change {{ }} to other symbols

### ISSUE THREAD

**Issue by error500** [ghiden/angucomplete-alt#214]
in order to work with blade templating (laravel), i had to change angular start-end symbols
 $interpolateProvider.startSymbol('<%');
 $interpolateProvider.endSymbol('%>');

Could be possible to enable this changes in paramters in angularcomplete-alt ?

**Comment by Boshen** [comment]
I would just provide my own custom template at this point :-)

**Comment by ghiden** [comment]
I thought it was difficult but turned out it wasn't.
Now it's automatic.

**Comment by error500** [comment]
Blade permit to escape the {{ }} with a @{{ }} so it's better doing so and removing
$interpolateProvider.startSymbol('<%');
$interpolateProvider.endSymbol('%>');

**Comment by ghiden** [comment]
If that's the case, you still need to provide your own template.
Using $interpolateProvider is the proper angular way to specify your own interpolate characters.
There was an issue #168 so I had to do this anyway.
