### ISSUE TITLE
adding a formSubmitHandler

### ISSUE THREAD

**Issue by webengineering2013-2014** [ghiden/angucomplete-alt#217]
Please, have a look at the following jsfiddle:

https://jsfiddle.net/ond9ps0s/2/

If one types in 'Denmark' for example and then submits the form the resulting POST request is:

testthis: Denmark

Is there an easy way to change that to

testthis: DNK

while keeping the title-field and search-fields equal to 'name'? Or even better does angucomplete-alt support some sort of "formSubmitHandler", where one can pass a function as parameter? Inside that function one could build a suitable form submission, which doesn't have to equal the input shown to the user.

Thanks!

**Comment by ghiden** [comment]
I would use callback and hidden field like this.
https://jsfiddle.net/yLnkeqa7/2/

**Comment by webengineering2013-2014** [comment]
This is a nice solution but it feels like this could be integrated into the directive as a feature (especially if one uses the directive in several places within the html code) so I was wondering whether this could be integrated into the angucomplete-alt directive? Instead of one internal input field, which is used by the directive for the view and the form submission one would have two internal input fields: One only for the view and one hidden input for the form submission. The default state would be that both fields have the same value. What do you think? This way one could avoid adding a hidden input "outside" the angucomplete-alt directive.

**Comment by ghiden** [comment]
I think form submission is not this directive's responsibility. I think parent controller/directive should handle it.
