### ISSUE TITLE
How to differentiate the search field, the field(s) displayed in the combo box and the field which will be set in the value input.

### ISSUE THREAD

**Issue by polom** [ghiden/angucomplete-alt#218]
HI,
First, thanks for this great directive.
One question I have : is there any way to differentiate the search field, the field(s) displayed in the combo box and the field which will be set in the value input ?
My main goal here is to have a search done by a certain field (this point is ok with : search-field), to have some fields displayed in the suggestion combobox (title-field="field1,field2" for instance) and to have a specific of the result object set in the input value.
Thanks in advance,
Paul

**Comment by ghiden** [comment]
Did you take a look at this?
https://github.com/ghiden/angucomplete-alt/issues/217

**Comment by ghiden** [comment]
Closing this for now as there is no reply.
