### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by nathanyeung** [ghiden/angucomplete-alt#220]
There is a JSON Parse Error on load of directive.

**Comment by ghiden** [comment]
Where?

**Comment by n8yeung** [comment]
I am using the plugin in my ionic project and I am getting a JSON parsing
error and a string unterminated error. I think it's in the find match
function which uses $sce.

On Tuesday, August 4, 2015, Hidenari Nozaki notifications@github.com
wrote:

> Where?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ghiden/angucomplete-alt/issues/220#issuecomment-127740386
> .

##

**Comment by ghiden** [comment]
JSON parsing is not part of this directive.
Please check to make sure the JSON you are getting is valid.

**Comment by n8yeung** [comment]
The JSON is valid the strict contextual evaluator runAsHtml function is
replacing the Characters in the regex expression

On Tuesday, August 4, 2015, Hidenari Nozaki notifications@github.com
wrote:

> JSON parsing is not part of this directive.
> Please check to make sure the JSON you are getting is valid.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ghiden/angucomplete-alt/issues/220#issuecomment-127755433
> .

##

**Comment by ghiden** [comment]
Please create a jsbin or plnkr example.

**Comment by nathanyeung** [comment]
How do I use the clearInput event?



On Tuesday, August 4, 2015, Hidenari Nozaki <notifications@github.com>
wrote:

> Please create a jsbin or plnkr example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ghiden/angucomplete-alt/issues/220#issuecomment-127757430>
> .
>


-- 

​
Nathan
​ Yeung
Coldwell Banker Apex, Realtors
®
7290 Virginia Parkway Suite 2400
McKinney, TX 75071
Cell: 972-251-0887​

**Comment by ghiden** [comment]
Did you solve the issue?

**Comment by n8yeung** [comment]
The errors disappeared on our end

On Tuesday, August 11, 2015, Hidenari Nozaki notifications@github.com
wrote:

> Did you solve the issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ghiden/angucomplete-alt/issues/220#issuecomment-129985741
> .

##
