### ISSUE TITLE
Property Not Required

### ISSUE THREAD

**Issue by zeeshanjan82** [ghiden/angucomplete-alt#224]
I have found an issue with the library which is related to the property name:

```js
 function httpSuccessCallbackGen(str) {
          return function(responseData, status, headers, config) {
            if (!status && !headers && !config) {
              responseData = responseData.data;
            }
            scope.searching = false;
            processResults(extractValue(responseFormatter(responseData), scope.remoteUrlDataField), str);
          };
        }
```
In the above code for the library the responseData.data property should be optional as the remote api might not have the data property.

**Comment by ghiden** [comment]
It's expecting a angular's http promise. So, it should have data property.

**Comment by zeeshanjan82** [comment]
If someone is using it with Restangular then he will surely have a hard time.

**Comment by ghiden** [comment]
Sorry I can't support all possible cases.

**Comment by zeeshanjan82** [comment]
@ghiden I understand. Thanks for the response
