### ISSUE TITLE
clearInput Event not working

### ISSUE THREAD

**Issue by nathanyeung** [ghiden/angucomplete-alt#225]
Hi ghiden,

How do I use the clearInput event? I added

$scope.clearSearch = function(id) {
     $scope.$broadcast('angucomplete-alt:clearInput', id);
};

but it doesn't do anything.

I ended up adding the following code under $scope.$broadcast('angucomplete-alt:clearInput')

 scope.clearInput = function(elementId) {
                  if (!elementId || elementId === scope.id) {
                      scope.searchStr = null;
                      callOrAssign();
                      handleRequired(false);
                      clearResults();
                  }
              };

and that worked!

**Comment by JohannesFerner** [comment]
+1 i couldn't get the current implementation to work either.
