### ISSUE TITLE
override-sugestions not working as expected

### ISSUE THREAD

**Issue by blackotruck** [ghiden/angucomplete-alt#226]
I'm ussing the override-sugestions options, but is always overwriting the sugestions, even when i'm selecting an object from the results array. If i remove the override-sugestions attribute the directive works fine, but i need to be able to select sugested values and overwrite them when no results

**Comment by ghiden** [comment]
It seems working fine to me. What are the exact user interactions that you are performing?

**Comment by blackotruck** [comment]
Type in, wait for suggestions, click on one of them. When i check inside the selected-object function for the selected object it has recived ``` {originalObject: "search text"} ``` where search text is what i typed, I know this is suppoused to happen when no suggestion is selected, but that is not the case
