### ISSUE TITLE
two way data binding

### ISSUE THREAD

**Issue by kishorpawar** [ghiden/angucomplete-alt#227]
Hey,

First of all thanks for such a beautiful directive.

I am modifying your directive to implementing two way directive. so I added `currentLocation : "="` this to scope : {} in directive. and passing  `current-location="currentLocation"` this in directive attributes.
Though when I set currentLocation on click of button before "touching" input field, It shows up in input field, But as soon as I try to type in input field, and then if I click button again to currentLocation, currentLocation gets set but does not shows up in input field.

what I want to do is here http://plnkr.co/edit/okbmQU1pwvKG1Y72zm0a?p=preview 

Thanks in advance for the help.

**Comment by kishorpawar** [comment]
Hey,

I solved this by just putting `currentLocation` in object.
so in controller I wrote `$scope.formData.currentLocation` and
in view I wrote `formData.currentLocation`. and
still I had to keep `currentLocation` in `tempVariable` to assign it back to `currentLocation` when directive changes it to ""(blank) value.

Thanks for such a lovely directive.

**Comment by shashykant** [comment]
I Hope this would help

https://github.com/ghiden/angucomplete-alt/issues/200
