### ISSUE TITLE
Order search results according to a different "algorithm" when using local data

### ISSUE THREAD

**Issue by nirshub** [ghiden/angucomplete-alt#228]
Great job on this amazing directive :)

I was looking for a way to re-order search results according to a different "algorithm". We want to give more weight to title matches over description matches.

We are using local data with a custom template.

At first, I tried using the "orderBy" filter on the "results" object. This seemed to work great, but after playing around with the results, I realised the Key Up and Key Down are no longer working as expected. Looking at the code, this makes sense as the search results and the "results" object are no longer in sync.

My first thoughts were to add another "hook" to the directive, which will be called during the processResults function call, with the results object. During this function call we could reorder the results as we wish.

I would like to hear your thoughts first before I go ahead and implement that.

Thanks!

**Comment by ghiden** [comment]
Just be careful when you use with match-class. You need to sort against some strings that contain html.

**Comment by nirshub** [comment]
OK thanks, it worked well :+1:
