### ISSUE TITLE
Remote-api-handler not working

### ISSUE THREAD

**Issue by LorDisturbia** [ghiden/angucomplete-alt#230]
Hello,
I'm having problems using your directive. I have set up a very simple autocomplete form:

    <angucomplete-alt pause="400"
                                   remote-api-handler="cardNumberAutocomplete"
                                   title-field="cardNumber"
                                   minlength="1"
                                   input-class="form-control" />

and I have defined this function in the controller

    $scope.cardNumberAutocomplete = function (userInputString, timeoutPromise) {
        return $timeout(function () {
            return [{ "cardNumber": "1" }, { "cardNumber": "2" }, { "cardNumber": "3" }]
        }, 1000);
However, even though the function is being called, I still get "No results" in the form. Why is it so? What am I doing wrong?

Thanks in advance

**Comment by LorDisturbia** [comment]
Ok I solved the problem. It looks like the directive expects an object like: 

{"data": [{ "cardNumber": "1" }, { "cardNumber": "2" }, { "cardNumber": "3" }]}

I suggest you write it explicitely in the docs.

Thanks,
Lorenzo

**Comment by ghiden** [comment]
Thanks for pointing it out. I've updated the README.

**Comment by rmrui** [comment]
> 
> 
> Ok I solved the problem. It looks like the directive expects an object like:
> 
> {"data": [{ "cardNumber": "1" }, { "cardNumber": "2" }, { "cardNumber": "3" }]}
> 
> I suggest you write it explicitely in the docs.
> 
> Thanks,
> Lorenzo

For some reason, I had to add in the directive (it wasn't clear for me until I tried):

remote-url-data-field="data" (in my case, data is my array).
