### ISSUE TITLE
The input should have the required attribute when field-required="true"

### ISSUE THREAD

**Issue by jmcollin78** [ghiden/angucomplete-alt#231]
When putting field-required="true" the underlying input doesn't have the required=required attribute.
So the standard form validation and class doesn't work as expected.

To make it work as expected you just have to add the following code at the end of line 52:
<pre>required="{{fieldRequired == \'true\' ? \'required\' : \'\'}}"</pre>

**Comment by cosminbondane** [comment]
if you don't want to change the code, you can use a custom html template (using template-url attribute). You can have something like this:

<input ... ng-required="{{fieldRequired}}" ng-change="inputChangeHandler(searchStr == undefined ? '' : searchStr)" />

**Comment by jmcollin78** [comment]
For those who can be interested in the response, here is the correct syntax:

 ng-required="fieldRequired"

**Comment by ghiden** [comment]
I'm not supporting this as it will only checks if the input field is filled or not. It does not check whether the field is filled with valid value or not.
