### ISSUE TITLE
Can't type into field

### ISSUE THREAD

**Issue by djbeckett** [ghiden/angucomplete-alt#233]
I can't type characters into the angucomplete-alt input field, but I can paste characters. If I paste chars, the lookups/dropdown works as it does on the demo page.

I've copied/pasted example 1 into my app because my own implementation had this problem and I wanted to go with something that I know works elsewhere. Neither mine nor the pasted example will accept typed chars. I know all the "wiring" is right because everything works as it should on both mine and the pasted example when I paste chars into the input.

Any ideas why I would not be able to type into the field? Other inputs on the form work fine. Just the angucomplete-alt input won't accept key strokes.

Thank you,
Dan

**Comment by ghiden** [comment]
Do you see any errors in dev console?
What browser are you using?
Can you create a jsbin or plnkr example?

**Comment by djbeckett** [comment]
Thank you for your reply.

No errors in the dev console.
Using Chrome Version 44.0.2403.157 (64-bit) on OS X 10.10.5
It works in plunkr, same code does not work in my app. 

My app is complex (multiple modues, ui-router, custom services, etc.), so it's hard for me to simplify the situation. I am fairly new to angular and web app dev, but not new to coding.

I was hoping someone may have had a similar experience and could give me a clue as to what might be causing it. I don't think it's necessarily the angucomplete-alt plugin, but I don't know what else to try or do.

Thank you,
Dan
