### ISSUE TITLE
Clicking outside field does not set value

### ISSUE THREAD

**Issue by nlitwin** [ghiden/angucomplete-alt#234]
I'm having trouble figuring out how to set the input value when clicking away from the field. Here is the user flow:

1) I type in United States
2) United States shows as the first option
3) Instead of selecting United States, I click somewhere else on the page, essentially blurring from the field
4) My form error pops up telling me that I didn't enter a valid country, because blurring from the field does not update the model value.

I noticed that tabbing away from the field does trigger a model change and selects whatever is first in the dropdown at that moment. I'd like to find a way to get the same functionality when clicking outside the field. I assume that the callback set in the selected-object attribute is not being called on blur? I tried focus-out, but had no luck.

**Comment by ghiden** [comment]
That's not supported. I usually check how other libraries handle this kind of behaviors. Twitter's typeahead does not do it for example. https://twitter.github.io/typeahead.js/examples/
If you want this feature, you have to add it yourself. Probably just add a hook to ng-blur would do.
