### ISSUE TITLE
Searching a simple Array 

### ISSUE THREAD

**Issue by pbhushan** [ghiden/angucomplete-alt#235]
Hi I am trying to search through a simple Array like ['item1','item2','item3'] but it doesn't work and when i search the array like [{'item' : 'item1' }, {'item' : 'item2' }, {'item' : 'item3'}] 
i am able to search perfectly. Is it possible to work also with Simple ArrayList. 
Thanks

**Comment by ghiden** [comment]
Nope. It can't work with an array of strings.

**Comment by pbhushan** [comment]
Thanks For a quick response.
