### ISSUE TITLE
404 (not found) error when using data loaded from api.

### ISSUE THREAD

**Issue by NickBehrends** [ghiden/angucomplete-alt#236]
So I am loading my data on page load from my API for the autocomplete to work. Here's how:

    $scope.employees = $scope.crud.getAll("employees", function(data, success) {
        if (success === true) {
            console.log("Success");
            console.log(data);
        } else {
            console.log("fail");
        }
    });

`getAll` is part of a generic factory the makes ajax requests:

    getAll: function (collection, callback) {
            $http({
                url: API_CONFIG.url + collection,
                method: 'GET',
                headers: { "Content-Type": "application/json;charset=utf-8" }
            }).success(function (data) {
                console.log(data);
                callback(data, true);
            }).error(function (data) {
                callback(data, false);
            });
        }

The data is returned as expected:

    [
      {
          "id": 4,
          "name": "William Steagall"
      },
      {
          "id": 5,
          "name": "Joao Furtado"
      },
      {
          "id": 6,
          "name": "Gregorio Rivera"
      },
      {
          "id": 7,
          "name": "Pedro Magana"
      },
      {
          "id": 8,
          "name": "Alicia Small"
      },
      {
          "id": 9,
          "name": "Gema Salvatierra"
      },
      {
          "id": 10,
          "name": "Trung Ta"
      },
      {
          "id": 11,
          "name": "Jorge Leon"
      },
      {
          "id": 12,
          "name": "Orlando Delgado"
      },
      {
          "id": 13,
          "name": "Jose Campos"
      }
    ]

The problem is when I try to use this data:

    <angucomplete-alt id="ex1"
                       placeholder="Search employees"
                        pause="100"
                        selected-object="selectedEmployee"
                         local-data="employees"
                         search-fields="name"
                         title-field="name"
                         minlength="1"
                         input-class="form-control form-control-small" />

I get `GET http://localhost:3000/undefinedw 404 (Not Found)` (localhost:3000 is the url of my api)

If I manually enter this data:

    $scope.employees = [
      { name: "Daryl", surname: "Rowland", twitter: "@darylrowland", pic: "img/daryl.jpeg" },
      { name: "Alan", surname: "Partridge", twitter: "@alangpartridge", pic: "img/alanp.jpg" },
      { name: "Annie", surname: "Rowland", twitter: "@anklesannie", pic: "img/annie.jpg" }
    ];

It works just fine. Any ideas?

**Comment by NickBehrends** [comment]
Fixed this, changed my factory to use promises.

**Comment by chandumatrix004** [comment]
Give the solution, how you did it??
I'm facing the same problem.
