### ISSUE TITLE
Problem on first element click if using initial-value

### ISSUE THREAD

**Issue by leandrogs** [ghiden/angucomplete-alt#238]
If I use initial-value on angucomplete-alt directive and the value is empty/null, I can't see elements name on first click.

```
<angucomplete-alt id="ex1" pause="100" selected-object="ticket.userCreator.email" local-data="ticketParams.clients" search-fields="name,email" title-field="name" minlength="0" input-class="form-control form-control-small" initial-value="ticket.userCreator.email"/>
```

Using angucomplete-alt as above, if I receive `ticket.userCreator.email` empty from database then select one element from dropdown list, nothing is show at input field. If I click AGAIN on the same (or other) dropdown list element it works fine (something is displayed at input). I have checked if the model is receiving the selected data and the answer is YES for every time I click on an element.

If data is passing to the model, why nothing is showed at the first time?

=======**EDIT**=======
I just figured out that I NEED to initialize my model. If it is undefined, the above problem occurs.

**Comment by ghiden** [comment]
I believe this is closed.

**Comment by p-bizouard** [comment]
I got the same issue. None initialized model lead to an empty value on the first click. I think it is an issue and should be checked.
