### ISSUE TITLE
Possible to use "Restrict attribute" with input?

### ISSUE THREAD

**Issue by TommySorensen** [ghiden/angucomplete-alt#241]
@ghiden 
Documentation says this is the way to do the element:

    <angucomplete-alt id="ex1"
              placeholder="Search countries"
              pause="100"
              selected-object="selectedCountry"
              local-data="countries"
              search-fields="name"
              title-field="name"
              minlength="1"
              input-class="form-control form-control-small"/>

But the code says you are also adding the directive on attribute (restrict: 'EA',)
I can get it to work with a input instead like this:

    <input
              angucomplete-alt
              type="text"
              id="ex1"
              placeholder="Search countries"
              pause="100"
              selected-object="selectedCountry"
              local-data="countries"
              search-fields="name"
              title-field="name"
              minlength="1"
              input-class="form-control form-control-small"/>

I can see in DOM that elements are added, but nothing happens when i type anything.

So the question is: Is is possible to use element <input> with attribute "angucomplete-alt" to activate the directive?

**Comment by ghiden** [comment]
I've never seen anyone using it with input tag.
Try using div.

**Comment by TommySorensen** [comment]
Forget the input :) My problem is that i wanne apply a directive to the input. Currently i am trying to use a directive with  classname selector on the input that is generated by angucomplete. But that's not possible to make it work in the correct "priority" order. My directive is applied before or after the angucomplete replacement. Therefor my directive never catches the input by the classname.

For example this directive would never work

	.directive('formControl', function() {
		return {
			restrict: 'C',
			link: function(scope, elem, attrs) {
				console.log(elem);

				if (elem[0].tagName !== 'INPUT' && !attrs.ngModel) {
					return;
				}

				console.log('do something with input');
			}
		};
	});

I tryed with timeout also, but didn't work.
