### ISSUE TITLE
Local-data fires server requests...

### ISSUE THREAD

**Issue by izkrivera** [ghiden/angucomplete-alt#243]
I am using the directive like this:

	<div angucomplete-alt
		id="keyword"
		input-name="keyword"
		placeholder="Job title or keywords"
		local-data="jobs"
		selected-object="selectedJob"
		search-fields="name"
		title-field="name"
		minlength="2"
		pause="100"
		input-class="form-control">
	</div>

And in the controller:

		$scope.jobs = [
			{"name": ".Net Developer"},
			{"name": "Account Coordinator"},
			{"name": "Account Director"},
			{"name": "Account Executive"},
			{"name": "Account Executive Sales"},
			{"name": "Account Executive Sales Representative"},
			...
		];
		
		$scope.selectedJob = function($item) {
			$log.info('$scope.selectedJob()', $item);
		};

But when I type on the field, an XHR request goes out to /undefinedWHATEVER_I_TYPED which is of course 404. No results from my jobs array are shown...

What am I doing wrong?

**Comment by izkrivera** [comment]
It was a scope issue.

**Comment by teamshultz** [comment]
I'm having this problem now. What was the issue?

**Comment by chorsnell** [comment]
@izkrivera @teamshultz I know this was 2 years ago, but what was the issue?
