### ISSUE TITLE
On title-field and description-field ignore undefined properties

### ISSUE THREAD

**Issue by Skyback** [ghiden/angucomplete-alt#244]
I'm fetching data from my server and the JSON response is something like:

{
...
    4: { id:2362, name: "XPTO", class: {description: "something"}  },
    5: { id:2454, name: "OTPX" , class: undefined},
...
} 

this happens because the specific object (2454) doesn't have the relation on the database. And angucomplete-alt is doing a simple map on the "title-field" and "description-field", causing undefined errors...
 
Can you adjust to simply ignore the property (or properties) on that specific object?

**Comment by ghiden** [comment]
Use remote-url-response-formatter to normalize your data.

**Comment by Skyback** [comment]
Thanks! That resolved my issue! ;)
