### ISSUE TITLE
Can't find a way to add a create when not found

### ISSUE THREAD

**Issue by jrgleason** [ghiden/angucomplete-alt#248]
I am using the auto complete to list all results of a query. Now I would like to add the functionality to allow me to include a create object link if it is not found. I will try to create a fork and implement but until then I am using this as a placeholder and also a forum for advise on this subject. Maybe there is a way and I just missed it.

**Comment by ghiden** [comment]
Sorry, it's not supported.

**Comment by jrgleason** [comment]
I forked and got it working fine I just didn't put in a merge request because the styling is still funny

**Comment by jrgleason** [comment]
*code styling

**Comment by kushal555** [comment]
@jrgleason  Can you please provide your solution here? Actually, i am also needed same.
