### ISSUE TITLE
auto-match doesn't play well with text-no-results in case of single match

### ISSUE THREAD

**Issue by artvlasov** [ghiden/angucomplete-alt#250]
When we have multiple unique options in dropdown, and user types exactly one of it, she sees textNoResult in dropdown. It's a bit confusing.

I've found a strange behaviour of processResults function:
```javascript
...
    if (scope.autoMatch) {
        checkExactMatch(...)
    }
...
```
It implicitly makes `scope.results` empty when user types string that exactly matches to a single variant, and because of it and of `displayNoResults` we have `scope.showDropdown` set to `true`.

I see an obvious fix to split search and underlying callOrAssign in checkExactMatch, and save result of checkExactMatch, so we could use it later to setup showDropdown.

I can prepare a PR if it could help.

**Comment by ghiden** [comment]
Thanks for reporting this. It is a bug. I'm releasing a fix soon.
