### ISSUE TITLE
Provide multiple search modes or custom matcher callback

### ISSUE THREAD

**Issue by scroach** [ghiden/angucomplete-alt#255]
Currently the module searches for any occurence in the searchable strings. I'd like to customize the search method (e.g., contains, startsWith, endsWith,...) or supply my own custom callback (accepting 2 values to compare).

Would it be easy to add such functionality?`

**Comment by ghiden** [comment]
I've been thinking about this feature but haven't got time to really work on this. It shouldn't be too hard. You just need to change getLocalResults function.

**Comment by ghiden** [comment]
Released v2.2.0.
