### ISSUE TITLE
angucomplete-alt on modal windows

### ISSUE THREAD

**Issue by physio** [ghiden/angucomplete-alt#256]
Good morning, sorry for my orrible english.

I'm trying angucomplete-alt and it seems really a good tool.
I'm writing an application with angular where I have a page with a table with a list of data and clicking the "edit" button opens a modal window where I can edit the field.

thanks to the example 9 can not upload in angucomplete the figure for the first array. But charging other arrays (rows in the table) as the initial object I always find the first array and not the updated one. I should initialize angucomplete whenever it changes the array, but I do not know how.

what 's the best solution to solve my problem?

**Comment by ghiden** [comment]
You should be able to update the array.
http://plnkr.co/edit/i3iQcg?p=preview

**Comment by ghiden** [comment]
If you need me to dig deeper, just open again.
