### ISSUE TITLE
Search only first letter for results 

### ISSUE THREAD

**Issue by ghost** [ghiden/angucomplete-alt#257]
Is it possible to return results by the first letter?

**Comment by ghiden** [comment]
No, currently the search method is fixed.
It's using indexOf.
I'm planning to add a custom search method that user can define your own method.
But I can't guarantee that it'll be coming soon or not.

**Comment by shashykant** [comment]
any updates on custom search implementation??

**Comment by ghiden** [comment]
@shashykant Sorry. I don't have time yet.

**Comment by nlitwin** [comment]
I need this feature too.

**Comment by radonirinamaminiaina** [comment]
We need this feature

**Comment by itsimoshka** [comment]
+1

**Comment by radonirinamaminiaina** [comment]
I added some features and send a pull request, test it into my local and it works. Could you review my code please? 

Thank you in advance

**Comment by nlitwin** [comment]
@radonirinamaminiaina I don't see your pull request, did you make a pull request yet?

**Comment by radonirinamaminiaina** [comment]
I tried to push my modification but I don't have the right access to the
repository.

This is the file I worked with.

2016-01-21 22:42 GMT+03:00 Nicholas Litwin <notifications@github.com>:

**Comment by ghiden** [comment]
I've created an experimental branch.
https://github.com/ghiden/angucomplete-alt/tree/custom-local-search
Try this and let me know if it works or not.

Just follow this discussion to see how to use the custom search.
https://github.com/ghiden/angucomplete-alt/issues/330

**Comment by ghiden** [comment]
Released v2.2.0.
I let you guys be creative about writing your own search function.
