### ISSUE TITLE
Attach to body

### ISSUE THREAD

**Issue by hackthis02** [ghiden/angucomplete-alt#264]
When I place the the autocomplate inside of a ng-modal, it gets cut off they at the bottom of the dialog. Can we add a way to attach it to the body to fix this?
![capture](https://cloud.githubusercontent.com/assets/7094667/10140615/1987b0fc-65ce-11e5-8f39-950ce79f8653.PNG)

**Comment by ghiden** [comment]
This is same as #221 
I won't fix it.
