### ISSUE TITLE
Choose value field

### ISSUE THREAD

**Issue by caleb-allen** [ghiden/angucomplete-alt#266]
I appreciate the 'title-field' attribute so I can choose what is set for the title. Is functionality for setting the value when the item is selected implemented?

For example, we have a specific ID we're using and a title associated with that ID. Our 'title-field' has both the ID and the title, but when the user selects it I only want to fill in the ID, which is another item in our JSON.

Any way I could achieve this?

**Comment by caleb-allen** [comment]
Never mind. I'm just using the selected-object callback to alter the fields afterwards.

**Comment by NickBehrends** [comment]
This option doesn't work that well if you have a lot of dropdowns on one page, handling selected-object for each drop down just to cast an id is realllly unnecessary and it's not good programming. Is there anyway this can be reopened for a fix or explanation of a better way?

**Comment by caleb-allen** [comment]
Sure. Some kind of functionality similar to 'title-field', but instead 'value-field' would be awesome, or as you say another way to achieve this instead of intercepting the selected-object callback.

**Comment by NickBehrends** [comment]
Thanks for re-opening. That's exactly what I'm thinking, while the existing option COULD work, it's just far from ideal.
