### ISSUE TITLE
Delayed API response causes dropdown to show even after text has been cleared.

### ISSUE THREAD

**Issue by JulianGriggs** [ghiden/angucomplete-alt#267]
This is a similar bug report to the one that was successfully closed in #254 

Version: v1.3.0
Options: 
```
id="My_id"
minlength="1"
maxlength="63"
placeholder="Placeholder"
pause="0"
selected-object="object"
input-changed="inputChangedFunction"
title-field="title"
remote-api-handler="ApiHandler"
```
If a user types an input which triggers the API call but then quickly use the delete key to clear their custom input the delayed API response, upon success, will cause the dropdown field to show even though the text in the input field has been cleared.

**Comment by ghiden** [comment]
Try this:
```js
scope.inputChangeHandler = function(str) {
  if (str.length < minlength) {
    cancelHttpRequest(); // cancel when input length goes shorter than required
    clearResults();
  }
 ...
```

**Comment by JulianGriggs** [comment]
From my testing, it seems to work great!

**Comment by ghiden** [comment]
Thank you @JulianGriggs 
I'll release the fix tonight in NZ time.
