### ISSUE TITLE
Is it possible to change the value of the angucomplete-alt input box via javascript?

### ISSUE THREAD

**Issue by sfaizan** [ghiden/angucomplete-alt#268]
i have a dropdown menu of items, upon selection of items from the list a form is pre filled, and one of the form item is an angucomplete-alt input box. i used 'initial-value' of angucomplete-alt to work this around, but it only works once, when i select another item from dropdown, the item in the angucomplete field is still the old one, i know that 2 way binding doesn't work in angucomplete, 

how do i go about filling the input box everytime i choose a new item from the dropdown?

**Comment by ghiden** [comment]
Send an event:
https://github.com/ghiden/angucomplete-alt#change-input
Have a look at this example:
http://ghiden.github.io/angucomplete-alt/#example16

**Comment by ghiden** [comment]
I'm closing this. If you need more help, please reopen it.
