### ISSUE TITLE
Is it possible to use Controller As syntax?

### ISSUE THREAD

**Issue by dkromp** [ghiden/angucomplete-alt#269]
if so, please describe...

**Comment by ghiden** [comment]
I'm not really actively following up angular lately.
"Controller As" syntax is something I don't really know.
Obviously it would probably won't work as I haven't done anything to support it.
I'll have a look if I can do anything about it.

This is a duplicate ticket so I'm closing this.
But could you add "+1" to #223?

**Comment by dkromp** [comment]
thx
