### ISSUE TITLE
Autocomplete field pop when setting initial value on IE

### ISSUE THREAD

**Issue by Nebulis** [ghiden/angucomplete-alt#270]
Hi,

On IE 11 (maybe in lower versions too), when using initial-value attribute, the autocomplete-field pop on start page. The bug is available in demo page.

It has been introduced by #239.

**Comment by ghiden** [comment]
Thanks for reporting this.
Yep, I just tested on IE9, 10, and 11.
IE9 works fine but 10 and 11 are no good.

**Comment by ghiden** [comment]
@Nebulis What OS are you running?

**Comment by Nebulis** [comment]
I tried on Windows 7

**Comment by ghiden** [comment]
It looks like it works on Windows 10 but releasing a fix now.

**Comment by ghiden** [comment]
Released v2.0.1

**Comment by Nebulis** [comment]
I just tried on Windows 10 and there isn't any bug, so maybe edge is really better than IE :)

Thanks for the fix !!

**Comment by TinoPham** [comment]
Thanks for the fixed!
