### ISSUE TITLE
IE11 quirk with how scope.searchStr updates

### ISSUE THREAD

**Issue by bulbulas** [ghiden/angucomplete-alt#272]
I've been trying to work out why the following occurs in IE11. 

type the letter 'a'
press ESC key
input box resets to empty instead of 'a'.

Looking at the keyupHandler scope.searchStr doesn't update in IE11 on every key stroke unlike in other browsers.

Reproducible using http://ghiden.github.io/angucomplete-alt/#example1
with the modern.IE IE 11 VM.

Not an issue using modern.IE Edge VM. firefox. chrome.

**Comment by ghiden** [comment]
Are you running it against v2.0.1? The web site was running v2.0.0 until a few minutes ago as I forgot to update it.

**Comment by bulbulas** [comment]
it's still happening with v2.0.1 on the demo site.

**Comment by ghiden** [comment]
Thanks for checking. I'll have a look.

**Comment by ghiden** [comment]
Released v2.0.2
