### ISSUE TITLE
Please add ability dynamically change text-no-results

### ISSUE THREAD

**Issue by itsimoshka** [ghiden/angucomplete-alt#273]
Hi!
Thank you for this awesome lib!
But I have a problem: my app supports internalization and when I change language I can change search results, but not **text-no-results** because of:
```javascript
scope.textNoResults = attrs.textNoResults ? attrs.textNoResults : TEXT_NORESULTS;
````
using **textNoResults** in **scope** section will solve my problem. The same is with **text-searching**.
Thank you!

**Comment by ghiden** [comment]
Do you want to 2-way bind these texts? You are not using any i18n framework?

**Comment by tecnicaz** [comment]
@itsimoshka try using text-no-results... After a lot of hair pulling I think I've got it.

**Comment by itsimoshka** [comment]
@ghiden not necessary 2-way bind. it will be enough '@' type variable in scope. I use angular-translate, but it just changes attribute text value, and in current implementation variable **scope.textNoResults** will not be changed after attr value change.

**Comment by Gusi** [comment]
It would be great to have this option to allow changing translations on-the-fly
