### ISSUE TITLE
Need an ability to custom-sort suggestions

### ISSUE THREAD

**Issue by shashykant** [ghiden/angucomplete-alt#274]
I need an ability to custom sort the suggestions in angu-complete-alt.

It runs great if I add the code at the bottom of getLocalResults() function.

matches = matches.sort(function(a, b)
{
return a.name.toString().indexOf(scope.searchStr)< b.name.toString().indexOf(scope.searchStr) ? 1 : -1
});

  scope.searching = false;
  processResults(matches, str);

I need an ability to pass the sorting method from consumed page.

I tried the code sample at http://plnkr.co/edit/SxaTGAbs9WbSaLPkrMlL?p=preview
please suggest changes.

**Comment by ghiden** [comment]
Have a look at this PR https://github.com/ghiden/angucomplete-alt/pull/258

**Comment by shashykant** [comment]
Hi I have made changes to angucomplete-alt.
this will now support custom sorting

https://github.com/shashykant/angucomplete-alt/blob/patch-1/angucomplete-alt.js
you can compare the changeshet https://github.com/shashykant/angucomplete-alt/commit/ab04af7a4e5641eb27d7b79b5fabf4ef6603a87c#diff-0b23162bfe8cb996d24ae2980605b539

simple pass a delegate to the directive, the beautiful job is done.

$scope.customsort = function(result, search)
{
   if(result && search)
  {
    return result.sort(function(a, b)
    {
      return a.name.toString().indexOf(search)< b.name.toString().indexOf(search) ? 1 : -1
      
    });
}
