### ISSUE TITLE
The plugin doesn't accept arrays as an input

### ISSUE THREAD

**Issue by craftbyte** [ghiden/angucomplete-alt#276]
I am using http://postcodes.io/ autocomplete using a remote API handler. since it returns something like [this](https://api.postcodes.io/postcodes/ox116a/autocomplete) I am unable to have the array in the autocomplete. Is it possible for the plugin to support arrays as input?

**Comment by ghiden** [comment]
You need to use remote-url-response-formatter to create an array of objects.

**Comment by craftbyte** [comment]
thanks, that worked
