### ISSUE TITLE
Error when using multi-step-container

### ISSUE THREAD

**Issue by sprintas** [ghiden/angucomplete-alt#277]
TypeError: Cannot read property '$setValidity' of undefined
    at handleRequired (angucomplete-alt.js:243)
    at angucomplete-alt.js:766
    at m.$broadcast (angular.min.js:137)
    at m.$destroy (angular.min.js:133)
    at angular-multi-step-form.js:186
    at angular.min.js:122
    at m.$eval (angular.min.js:134)
    at m.$digest (angular.min.js:131)
    at m.$apply (angular.min.js:135)
    at HTMLButtonElement.<anonymous> (angular-touch.js:477)

<div angucomplete-alt id="brct_id" placeholder="Select" pause="100"
                     selected-object="selected.city" local-data="cities" search-fields="city_name"
                     title-field="city_name"
                     initial-value="selected.city.originalObject"
                     minlength="1" input-class="form-control form-control-small" match-class="highlight"
                     field-required="requireCity" input-name="city">
                </div>

**Comment by ghiden** [comment]
What is multi-step-container?

**Comment by sprintas** [comment]
Hello,

More info eitch form I using, when click next I got error on form
validation.

https://github.com/troch/angular-multi-step-form

On 2015 spal. 18, sk at 10:58, Hidenari Nozaki <notifications@github.com>
wrote:

> What is multi-step-container?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ghiden/angucomplete-alt/issues/277#issuecomment-148987761>
> .
>
-- 
Pagarbiai
Rimantas

**Comment by ghiden** [comment]
I've never used that multi-step-form before.

What version of angular are you using?
Probably it's complaining that angucomplete-alt cannot find a form controller.
Is there any form and does it have a name?

**Comment by jmcollin78** [comment]
Same problem for me with 2.0.2 release.
It occurs only when you have a require field (field-required="true"). When the form is destroyed the code check for required validity but input is destroy.
Cf. line 764 of code:
<pre>
scope.$on('$destroy', function() {
        // take care of required validity when it gets destroyed
        handleRequired(true);
      });
</pre>
and line 239:
<pre>
function handleRequired(valid) {
        scope.notEmpty = valid;
        validState = scope.searchStr;
        if (scope.fieldRequired && ctrl && scope.inputName) {  /!\ this test is ok but ctrl[scope.inputName] is null
          ctrl[scope.inputName].$setValidity(requiredClassName, valid);
        }
      }
</pre>
You should replace line 242 by this one:
<pre>
 if (scope.fieldRequired && ctrl && scope.inputName && ctrl[scope.inputName])
</pre>

I think this will fix the issue.

JM.

**Comment by jmcollin78** [comment]
Another precision, I have modified the template to have to require set if field-required option is set:
<pre>
     ...
     <input id= .....  ng-required="fieldRequired"/>    // line 4 of template
    ....
</pre>

**Comment by sprintas** [comment]
Thank, you very much.

Pagarbiai/
Best regards,


Rimantas

---------------------------------------------------------------
e-mail: r.zakauskas@gmail.com

**Comment by ghiden** [comment]
@jmcollin78 Thank you for debugging this. Could you try removing the whole $destroy block? It was actually old code for required to work in angular 1.2. I don't this it's relevant anymore. If it works, I'll remove it from code.

**Comment by jmcollin78** [comment]
@ghiden I remove the block and all seems to be ok with angular 1.4.7 and release 2.0.2 of angucomplete-alt.

**Comment by ghiden** [comment]
@jmcollin78 Great! Do you want to create a PR?

**Comment by jmcollin78** [comment]
Sorry but I don't really have time to fork, modify tests and push. Sorry I'm very busy.

**Comment by ghiden** [comment]
@jmcollin78 Thanks for your reply. I'll release it soon.
