### ISSUE TITLE
How to prevent stripping HTML from shown values

### ISSUE THREAD

**Issue by poisa** [ghiden/angucomplete-alt#278]
angucomplete-alt seems to be escaping my html so it looks like this "Hello \<b>World\</b>"
instead of actually parsing the HTML and showing "Hello **World**".

I'm referring to the auto-complete menu that appears as you type. Is there a way to disable this? I'm using local data that I can trust so this wouldn't pose a security threat.

**Comment by ghiden** [comment]
Sorry, that's not possible.
I also find matching part against the given data, so if you provide html in the data, it won't match either.
Not a simple fix that I can provide.
