### ISSUE TITLE
field-required without input-name not working

### ISSUE THREAD

**Issue by axos88** [ghiden/angucomplete-alt#279]
Please fix or docuemnt that the classes do not get applied in this case.

**Comment by ghiden** [comment]
That's how angular works.
https://docs.angularjs.org/guide/forms

> Binding to form and control state
> A form is an instance of FormController. The form instance can optionally be published into the scope using the name attribute.

> Similarly, an input control that has the ngModel directive holds an instance of NgModelController. Such a control instance can be published as a property of the form instance using the name attribute on the input control. The name attribute specifies the name of the property on the form instance.

I'll update the doc for clarification.
