### ISSUE TITLE
Examples page doesn't work

### ISSUE THREAD

**Issue by alexandrz** [ghiden/angucomplete-alt#280]
I am getting error both in ff and chrome:

```
Blocked loading mixed active content "http://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular.min.js"[Learn More] angucomplete-alt
Blocked loading mixed active content "http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.6/angular-touch.min.js"[Learn More] angucomplete-alt
TypeError: angular is undefined angucomplete-alt.js:25:3
ReferenceError: angular is not defined
```

**Comment by ghiden** [comment]
Just tested on Chrome, Chrome Canary, FF, FF dev edition, and Safari on my mac.
They all work fine.

**Comment by benjamincharity** [comment]
@alexandrz I saw the same thing.. if you load the example on an `https` connection you will see this error. Load the example page with just `http` and it should work.

**Comment by alexandrz** [comment]
@benjamincharity thanks. I have HTTPS-Everywhere installed

**Comment by ghiden** [comment]
I'm closing this.

**Comment by benjamincharity** [comment]
@alexandrz yeah I do too. I have to open the examples in an incognito window
