### ISSUE TITLE
Example of updating hidden input? or ngModel?

### ISSUE THREAD

**Issue by snobrdinrtiste** [ghiden/angucomplete-alt#281]
I have read thru all the requests/questions/issues and maybe i missed it ... but seems like there is no support to use ngModel in the directive itself...
so is there a current example of getting the autocomplete value into another input field?... so that the input is linked to an ngModel?
or whatever way everyone is using... to grab that final autocomplete value.
thanks for your time,
derek

**Comment by ghiden** [comment]
You are right. There is no 2-way binding.
You need to use a scope variable or callback function.

**Comment by snobrdinrtiste** [comment]
So are there any examples i can take a look at? 
Or can i use ng-blur on the html element to a function?

**Comment by ghiden** [comment]
I would probably use a callback function.
http://ghiden.github.io/angucomplete-alt/#example7

**Comment by snobrdinrtiste** [comment]
thanks for your help ghiden

**Comment by snobrdinrtiste** [comment]
sorry for closing this thread prematurely...
i have another question... 
i am using the focus-out event  and how do i get the control's text without selecting from the autocomplete dropdown?
for instance... if I type "united states of america" into the input field, and then press enter or tab...
it will fire the focus-out event.  and in that focus-out function, how would i get the value "united states of america"?

**Comment by snobrdinrtiste** [comment]
ok nvm... i totally missed the selected.originalObject  
everything is good now :)
