### ISSUE TITLE
cannot call setValidity on undefined

### ISSUE THREAD

**Issue by axos88** [ghiden/angucomplete-alt#287]
Hello,

My complete tag is defined like this:

```
            <angucomplete-alt
                    placeholder="Select user..."
                    pause="100"
                    selected-object="setCustomerUser"
                    local-data="customerusers"
                    search-fields="login"
                    title-field="login"
                    description-field="name"
                    minlength="0"
                    field-required="true"
                    auto-match="true"
                    input-name="user"
                    input-class="form-control"></angucomplete-alt>
```

When I change the page using ngRoute, i get the following exception (but the app continues to run okay):

```
TypeError: Cannot read property '$setValidity' of undefined
    at handleRequired (angucomplete-alt.js:243)
    at angucomplete-alt.js:766
    at Scope.parent.$get.Scope.$broadcast (angular.js:16311)
    at Scope.parent.$get.Scope.$destroy (angular.js:15923)
    at cleanupLastView (angular-route.js:909)
    at angular-route.js:942
    at publicLinkFn (angular.js:7554)
    at name.$get.boundTranscludeFn (angular.js:7699)
    at controllersBoundTransclude (angular.js:8316)
    at update (angular-route.js:935)
```

This is on a Chrome running on MacOS X

**Comment by ghiden** [comment]
Are you using v2.0.3?

**Comment by axos88** [comment]
v2.0.2

**Comment by axos88** [comment]
Upgraded to v2.0.3, fixed.

**Comment by salluu** [comment]
Its still not working for me  using  <angucomplete-alt id="ex1"
                                  placeholder="type to search model..."
                                  pause="100"
                                  selected-object="selectedModel"
                                  local-data="allProducts"
                                  search-fields="MarketingName,ModelCode"
                                  title-field="ModelCode,MarketingName"
                                  minlength="2"
                                  input-class="form-control"
                                  field-required="true"
                                  auto-match="true"
                                  input-name="user"
                                  initial-value="updateModel" />

**Comment by ghiden** [comment]
@salluu what error are you getting? Are you using angular 1.2 or 1.4? Do you have a form controller?

**Comment by salluu** [comment]
i am using same  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular.min.js"></script>
      <script src="http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.6/angular-touch.min.js"></script>

what do you mean by form controller 
```
  <form name="registerProductForm" role="form" method="post" ng-submit="registerProduct($event)">

        <div class="form-group">
            <label>Model</label>
            <p>
                <angucomplete-alt id="ex1"
                                  placeholder="type to search model..."
                                  pause="100"
                                  selected-object="selectedModel"
                                  local-data="allProducts"
                                  search-fields="MarketingName,ModelCode"
                                  title-field="ModelCode,MarketingName"
                                  minlength="2"
                                  input-class="form-control form-control-small"
                                  field-required="true"
                                  match-class="highlight"
                                   input-name="country8a"
                                  initial-value="updateModel" />
            </p>
```

**Comment by ghiden** [comment]
I just wanted to make sure you have a form. But it looks fine to me. If you can create a plnkr or jsbin example, I can have a look.

**Comment by axos88** [comment]
You don't have a name on your angucomplete field.
