### ISSUE TITLE
Unrecognized field "title" not marked as ignorable

### ISSUE THREAD

**Issue by belchel** [ghiden/angucomplete-alt#288]
I'm using Jersey and Jackson for JSON mapping. I tried with @JsonIgnoreProperties(ignoreUnknown=true) , but it didn't work and it still throwing this exception: 

Unrecognized field "title" not marked as ignorable

Any ideia?

**Comment by ghiden** [comment]
Jersey and Jackson are java libraries, right?
I don't know how your REST API behaves, so I have no idea.
If you can paste a log from curl, I might be able to say something.

**Comment by belchel** [comment]
I saw that it's trying to save the hole selectedObject instead of originalObject.  selectedObject has another properties different from my model, then it's throwing this error. I need to take only the origininalObject.  
But another problem comes... how to show the originalObject back to selectObject...

**Comment by ghiden** [comment]
Use callback? http://ghiden.github.io/angucomplete-alt/#example7

**Comment by belchel** [comment]
Now it's always showing "no results found"

**Comment by ghiden** [comment]
All I need is your API response and your js code.
Without it, I can't debug.
Or please study all the examples first and come back to me.
I don't think your case is particularly unique.

**Comment by belchel** [comment]
Oh i saw it in your example:
$scope.countrySelectedFn9 = function(selected) {
      if (selected) {
        $scope.countrySelected9 = selected.originalObject;
      } else {
        $scope.countrySelected9 = null;
      }
    }

You could put these in JSFiddle or something, because I needed to inspect your code hehe.

**Comment by ghiden** [comment]
Dev console is your friend when it comes to js development.

If your issue is gone, please close it.
