### ISSUE TITLE
Img Base64

### ISSUE THREAD

**Issue by Bernardoow** [ghiden/angucomplete-alt#289]
Hey Guys!!!

I have a probleman! 
Can I use img Base64? IF yes, how do I do it?

**Comment by ghiden** [comment]
How do you want to use it?

**Comment by Bernardoow** [comment]
HI GHiden,

I receive IMG Base64 on Json. But image-field is not working with base64.

**Comment by ghiden** [comment]
What's the exact format of image attribute? If it doesn't have "data:image/png;base64," at front, you just need to prepend this using remote-url-response-formatter.

**Comment by Bernardoow** [comment]
OK THX FOR awnser
