### ISSUE TITLE
Reset input after submit

### ISSUE THREAD

**Issue by aganglada** [ghiden/angucomplete-alt#293]
Hello guys,

I've been trying to reset the input after I do submit a form in which the angucomplete-alt is inside, but I had no success, I thought if I reset the selected-object model it will be reseted, but it doesn't. Do you know how does it work? Or how to reset it?

```
<div angucomplete-alt
       id="users"
       input-name="users"
       placeholder="Look for users..."
       pause="400"
       minlength="2"
       selected-object="usersView.model.user"
       remote-url="{{ usersView.form.url }}?limit={{ usersView.form.limit }}&search="
       remote-url-data-field="results"
       title-field="sEmail"
       field-required="true"
       input-class="form-control"
></div>
```

Thanks in advance.

**Comment by ghiden** [comment]
Use clear-input https://github.com/ghiden/angucomplete-alt#clear-input

**Comment by aganglada** [comment]
Working nicely! Thank you very much
