### ISSUE TITLE
Autocomplete appears transparent

### ISSUE THREAD

**Issue by mattfili** [ghiden/angucomplete-alt#302]
Having an issue where autocomplete dropdown appears transparent (note the screenshot).  
* I attempted adding a high z-index rule (e.g., z-index: 1000) and background-color: #fff to the following attributes to no-avail .angucomplete-holder, angucomplete-dropdown, angucomplete-searching, angucomplete-row, angucomplete-selected-row
* Upon searching stackoverflow I found similar issues related to a dependency named j-query-ui although it does not appear to be a dependency of angucomplete-alt. 

Any support or a point in the right direction will be thoroughly appreciated

![screen shot 2015-11-09 at 12 48 17 pm](https://cloud.githubusercontent.com/assets/3579105/11046130/2b3f8344-86f1-11e5-9e5c-17826adb095a.png)

**Comment by ghiden** [comment]
What's the z-index of 'How it works'?

**Comment by ghiden** [comment]
I'm closing this as no one else is complaining. Please re-open this if you need more help on this.
