### ISSUE TITLE
Event on selected list item

### ISSUE THREAD

**Issue by Matthewloughton** [ghiden/angucomplete-alt#308]
Good day,

I need a function to fire as soon as a user selects a list item (in the suggested list). I have scoured the internet for an answer, but I only found this: http://stackoverflow.com/questions/26367277/angucomplete-fire-event-when-value-is-selected-in-angularjs
which actually led me to use angucomplete-alt instead of the standard angucomplete however I have not found a solution.

Some backgroud of what I need to do:
input box with autocomplete which searches through a list of locations (array of objects) that contain a latitude and longitude (done, works like a charm btw). When the user selects a location from the list, it needs to run a function that passes in the location object and then adds location (using lat and long of that location object) to a map.

I've tried input-changed but that only triggers when user is typing inside the input box. I tried both focus-in and focus-out but it did not help.

Looking forward to your response.

**Comment by ghiden** [comment]
You can either watch the selected object or use callback.
I think callback is easier.
Have a look at the example 7
http://ghiden.github.io/angucomplete-alt/#example7

**Comment by Matthewloughton** [comment]
OK this has helped me a bit. I've hit a bit of a wall at the moment, but its because I'm using two angucompletes inside a repeater so manipulating the objects like I need to becomes a bit confusing.

Thanks for your prompt response though. I'll let you know if I run into anymore issues.

**Comment by Matthewloughton** [comment]
The only problem I have with this as a solution is now the input box isn't bound to a model anymore. I have angucomplete inside of a repeater. I'm fairly new to angular however most other directives I have used will bind a model to the control and then have events such as "dragend", "dragged" where you can specify functions and not lose the model bound to the control.

**Comment by ghiden** [comment]
Have you tried this?
https://github.com/ghiden/angucomplete-alt#callback-behaviour

**Comment by Matthewloughton** [comment]
What i was trying to do is render up the angucomplete in the repeater with a json object (user viewing something that was saved). I found a solution, not sure why I didnt think of it before but I've just swapped out the angucomplete boxes for normal input boxes when the user is viewing the information, they can't edit whats been saved so I asked myself "why do they need the autocomplete functionality?" 

Ciao

**Comment by ghiden** [comment]
Is it ok to close?
