### ISSUE TITLE
Custom templating, where is "my-custom-template.html" or a working example ?

### ISSUE THREAD

**Issue by alaraki-publicis** [ghiden/angucomplete-alt#309]
Hello,

First of all, thank you for this awesome work !

I want to customize the result rendered. The documentation and example 14  say's to use the attribute << template-url="/my-custom-template.html" >> to achieve that.

But i just can't find anywhere this "my-custom-template.html" or another example of custom templating. Since i m not good enough to guess how the page should be, i am stuck.

Could you provide an example please ? 

Thank you again for your awesome work :+1: 
AL

**Comment by alaraki-publicis** [comment]
To answer my own question, after searching again, i found the default template : 

<div class="angucomplete-holder" ng-class="{'angucomplete-dropdown-visible': showDropdown}">
    <input id="{{id}}_value" name="{{inputName}}" ng-class="{'angucomplete-input-not-empty': notEmpty}" ng-model="searchStr" ng-disabled="disableInput" type="{{inputType}}" placeholder="{{placeholder}}" maxlength="{{maxlength}}" ng-focus="onFocusHandler()" class="{{inputClass}}" ng-focus="resetHideResults()" ng-blur="hideResults($event)" autocapitalize="off" autocorrect="off" autocomplete="off" ng-change="inputChangeHandler(searchStr)" />
    <div id="{{id}}_dropdown" class="angucomplete-dropdown" ng-show="showDropdown">
        <div class="angucomplete-searching" ng-show="searching" ng-bind="textSearching"></div>
        <div class="angucomplete-searching" ng-show="!searching && (!results || results.length == 0)" ng-bind="textNoResults"></div>
        <div class="angucomplete-row" ng-repeat="result in results" ng-click="selectResult(result)" ng-mouseenter="hoverRow($index)" ng-class="{'angucomplete-selected-row': $index == currentIndex}">
            <div ng-if="imageField" class="angucomplete-image-holder">
                <img ng-if="result.image && result.image != ''" ng-src="{{result.image}}" class="angucomplete-image" />
                <div ng-if="!result.image && result.image != ''" class="angucomplete-image-default"></div>
            </div>
            <div class="angucomplete-title" ng-if="matchClass" ng-bind-html="result.title"></div>
            <div class="angucomplete-title" ng-if="!matchClass">{{ result.title }}</div>
            <div ng-if="matchClass && result.description && result.description != ''" class="angucomplete-description" ng-bind-html="result.description"></div>
            <div ng-if="!matchClass && result.description && result.description != ''" class="angucomplete-description">{{result.description}}</div>
        </div>
    </div>
</div>

**Comment by tribridge-jonathanmbeck** [comment]
was this ever answered?  How do I insert my own template, and what is the path relative to?

**Comment by tribridge-jonathanmbeck** [comment]
After trying to get the template-url param to work OOB I decided to branch the directive and make my own version with a regular templateUrl to an .html file.

**Comment by stamminator** [comment]
@tribridge-jonathanmbeck `template-url` is not working for me either, however `templateUrl` works, and I certainly don't have your branch. I think `templateUrl` works OOB
