### ISSUE TITLE
Select an attribute of an object in the selected object.

### ISSUE THREAD

**Issue by peche11** [ghiden/angucomplete-alt#310]
For example you have the following code:
# Controller:
```javascript
$scope.books = [{"name":"book1","year":2012,"author":{"name":"Jose","lastname":"solis"}},{"name":"book2","year":2013,"author":{"name":"Jose","lastname":"solis"}},{"name":"book3","year":2014,"author":{"name":"Jose","lastname":"solis"}},{"name":"book4","year":2015,"author":{"name":"Jose","lastname":"solis"}}]
```
# View:
```html
<div angucomplete-alt id="Txt_book" placeholder="Select a book" pause="100" matchclass="highlight" selected-object="selectedBook" local-data="books" search-fields="name,year" title-field="name,year" minlength="1" input-class="form-control form-control-small" match-class="highlight">
```

Is there a way to show the name and the last name of the author in the title-field?

I tried doing something like:  title-field="name,year,author.name,author.lastname". 
But that doesn't work.

Thanks.

**Comment by ghiden** [comment]
What are you trying to do?
![2015-12-03 21 41 15](https://cloud.githubusercontent.com/assets/17842/11555653/c5bdd9ac-9a06-11e5-91bc-b2490b487567.png)

**Comment by peche11** [comment]
Yeah, I wanna do the same that you in the example.

**Comment by ghiden** [comment]
Nothing special, I did what you describe.
```html
<div angucomplete-alt id="ex1" placeholder="Search" maxlength="50" pause="100" selected-object="selectedBook" local-data="books" search-fields="name,year" title-field="name,year,author.name,author.lastname" minlength="1" input-class="form-control form-control-small" match-class="highlight"> 
```

**Comment by peche11** [comment]
Does do it with "$scope.$broadcast('angucomplete-alt:changeInput', 'autocomplete-1', book);" and has by selected-object a callback affect in something?

**Comment by ghiden** [comment]
I think it should update. It doesn't?

**Comment by peche11** [comment]
When I do it the input set as empty.

**Comment by ghiden** [comment]
It should work. What is "book" that you sending in $broadcast?

**Comment by peche11** [comment]
I did another way. Thanks for your help and quick answer.
