### ISSUE TITLE
angucomplete-alt Input Changes

### ISSUE THREAD

**Issue by HADDAD-Riadh** [ghiden/angucomplete-alt#315]
first thank you for this good tutorial ,it is verry useful ,
i have difficultie to change the value of the angucomplete 
this is my code .
 i tested with $scope.$broadcast('angucomplete-alt:clearInput', 'nomGC'); and it is OK ,it clear the input field but when i call change ,the input is not updated

 

this is my angucomplete :
********************************************
           <angucomplete-alt
            input-name="nomGC"
            id="nomGC" 
            pause="100" 
            selected-object="Selected"
            search-fields="libelle" 
            title-field="libelle,code" 
            minlength="3" 
            local-data="libelles_pec"
            input-class="form-control spinner_grand-compte "
            match-class="highlight" 
            override-suggestions="true"
            field-required="true" 
            class="ng-isolate-scope"
            minlength="1" 
            disable-input="disableInput"
            focus-in="focusIn()"
            focus-out="focusOut()"
            >
****************************************
and this is my controller function to chage value input

$scope.changeInput = function (id) {

  $rootScope.$broadcast('angucomplete-alt:changeInput', id, {code: "MK", libelle: "AGP"});			      
	}	

*********************************************
and this is my link to change call changeInput
 < a ng-click="changeInput('nomGC')" >change compte value< /a > 

please help thanks

**Comment by ghiden** [comment]
It looks legit to me.
Any error are you getting?

**Comment by HADDAD-Riadh** [comment]
No sir ,i tested but no chance



*Bien Cordialement ,*

*----------------------------------------------------------------------------------------------------*
*HADDAD Riadh *


*Ingénieur études et developpement *

*Mobile :+33 6 34 12 31 09      (07 54 11 58 40)*

2015-12-09 17:38 GMT+01:00 Hidenari Nozaki <notifications@github.com>:

**Comment by ghiden** [comment]
If you create a plnkr or jsbin example, I can have a look.

**Comment by HADDAD-Riadh** [comment]
ok i will create one in 10 minutes thanks

**Comment by HADDAD-Riadh** [comment]
this is the link 
http://plnkr.co/edit/Md93I8zRiUNkXxXjMKJP?p=preview
thank you

**Comment by ghiden** [comment]
You are not using the latest version. Your angucomplete-alt.js source code doesn't have $on for changeInput. Get the latest and try it again.

**Comment by HADDAD-Riadh** [comment]
i used the last versionas you can see

**Comment by HADDAD-Riadh** [comment]
yeeeeeees it works now, thank you verry much
