### ISSUE TITLE
Local static JS/JSON file as search results?

### ISSUE THREAD

**Issue by Chirpizard** [ghiden/angucomplete-alt#321]
First, thanks for this module!

I'm new to Angular so trying to figure this out. If I want to move my array of objects out of the controller into their own JS(or JSON later) file. So how would I point my $scope variable to the array of objects from another file? I thought that remote-url would do the trick but when I add the url as the value it doesn't find results from there.

What am I doing wrong?

I understand probably just falls under general Javascript knowledge, but this seems like the best place to figure it out.

Thanks again!

**Comment by ghiden** [comment]
You don't want to use remote-url because it needs to be a search end point that responds to a query string. So, you need to use it as local.
You need to do something like this:
```js
// Inside your controller, initialize an empty array
$items = [];

// load the file
$http.get('some-data-file.json').then(function(response) {
  angular.copy(response.data, $items);
});
```

**Comment by Chirpizard** [comment]
Would a regular js file that contains an array of objects work the same? I'm trying this now:
````
    $gameObjects = [];

    $http.get('gamedata.js').then(function(response) {
       angular.copy(response.data, $gameObjects);
    });
````

Then my directive uses
````
local-data="gameObjects"
````

But when I search for something, lets say the term "iron" i get a 404 not found in console:
`http://localhost:8888/merchant/undefinediron`

Everything works fine if I just have the array of objects inside of the controller.

**Comment by ghiden** [comment]
It needs to be an array of objects.
Please check out the examples:
http://ghiden.github.io/angucomplete-alt/

**Comment by Chirpizard** [comment]
It is an array of objects.
````
//gamedata.js
var gamedata = [
   {data},
   {data},
];

Like I said, using the exact same array of objects in the controller works.

**Comment by Chirpizard** [comment]
I looked over the examples, they helped me solve a few other problems I was having. I don't see one that does this though.

**Comment by ghiden** [comment]
What's your json look like?

**Comment by Chirpizard** [comment]
http://pastebin.com/raw/0RsJsDJJ

**Comment by ghiden** [comment]
Are you serving files from http server? If you serve files via file protocol, xhr won't work. You have to run some sort of http server to serve local files.

Anyway, here is a complete example for you:
http://plnkr.co/edit/Si4dBL?p=preview
