### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by tirumalavasu** [ghiden/angucomplete-alt#323]
I am using angucomplete-alt in a mean stack app.

I am getting this error

Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

![angu](https://cloud.githubusercontent.com/assets/3540345/12134927/9cd73448-b45a-11e5-8285-eb184b52d6a9.jpg)

**Comment by ghiden** [comment]
I've never tested on Chromium. Try adding a polyfil for getComputedStyle.

**Comment by Boshen** [comment]
window.getComputedStyle works. 

Why is your code accessing `Window` not `window`?

**Comment by tirumalavasu** [comment]
I am using angucomplete-alt inside a modal dialog (Angular Material) and i am using 3 in total in my application. After using one, the other one gives this error. Initially i am not getting this error.

**Comment by Boshen** [comment]
Well, the source code computes `getComputedStyle` on `elem[0].querySelector('.angucomplete-dropdown')`. Perhaps your directive setup is not correct, hence the error.

**Comment by ghiden** [comment]
I'm closing this. If you still need some help, please re-open it.

**Comment by tirumalavasu** [comment]
When i changed my code from "Controller As" syntax to "Controller" syntax, it's working fine. Don't know the exact reason. Just for your info.

**Comment by ghiden** [comment]
@tirumalavasu Thanks for letting me know. I'm not familiar with "Controller As" syntax but probably that's it. I'll keep it in mind.

**Comment by agupta330** [comment]
how did you resolve that issue i am also getting same error in my mean stack application @tirumalavasu @ghiden

**Comment by tirumalavasu** [comment]
@agupta330  i changed my controller syntax from "Controller As" to "Controller". I mean using $scope instead of "this" worked for me.

**Comment by alexg313** [comment]
I'm getting the same error, but moving away from the "Controller as" syntax is not an acceptable solution.

**Comment by smartfoxes** [comment]
I had the same error, but problem was in my custom template markup - it was missing class name  "angucomplete-dropdown" (likely older variation of the template)

**Comment by alexg313** [comment]
@smartfoxes I'm running into the same issue. Did you add class="angucomplete-dropdown" to the template script?

**Comment by alexg313** [comment]
Ok, figured it out. If you're using a custom template, you need to have the "angucomplete-dropdown" class on the element containing the results. Something like: 

<div class="angucomplete-dropdown...> 
 // your dropdown results
</div>
