### ISSUE TITLE
Customizing rows in template to show more than Title/Image/Description

### ISSUE THREAD

**Issue by handonam** [ghiden/angucomplete-alt#326]
I was looking into this autocomplete, and I like the work that's been done with it! It's lightweight, and has almost everything I need.  However, I'm not sure about the capabilities of the following:

With [Angular Material](https://material.angularjs.org/latest/demo/autocomplete), If i search for "Angular 1", it shows me the number of watchers and forks (3,623 watchers, 16,175 forks) .  However, looking at angucomplete, it seems as though if I did something similar by putting this in angucomplete's "description", I could potentially type "3,623" and end up unwillingly getting "Angular 1" to show up.

I ultimately want to have the following fields to customize my row:

`product name` -> angucomplete title
`product picture` -> angucomplete image
`product description` -> angucomplete description
`number of people with product` -> ??

The last row is the missing piece. Is there something I'm missing? Is there a way to achieve that?

Thanks!

**Comment by ghiden** [comment]
Sorry for my late reply.
This directive has only three fields to present for a row, so it can't show "number of people with product".

**Comment by mgohin** [comment]
Can't the directive pass raw result objects ?

Kinda need it too in a custom template

**Comment by mgohin** [comment]
Just digged into the code, found `originalObject` in the result object ;)
