### ISSUE TITLE
Impossible to get Nested Field

### ISSUE THREAD

**Issue by thugyac** [ghiden/angucomplete-alt#327]
Hello, 

How can we access on the nested field on angucomplete ? The "dot" are not working. 
There is an example of the code : 

The JSON data on the $scope.countries : -------
```
[{
	"id": 1,
	"name": "Senegal",
	"continentName": "Africa",
	"cities": [{
		"id": 1816,
		"name": "Dakar",
		"countriesId": 1
	}, {
		"id": 1820,
		"name": "Saint-Louis",
		"countriesId": 1
	}]
}, {
	"id": 2,
	"name": "Mali",
	"continentName": "Africa",
	"cities": [{
		"id": 1286,
		"name": "Bamako",
		"countriesId": 2
	}]
}]
```
And the angular view : --------- 

```
<div angucomplete-alt id="activities" placeholder="Where are you going ?" pause="100" selected-object="activitiesSelected" local-data="countries" search-fields="name,cities.name" description-field="name" title-field="cities.name" minlength="1" input-class="form-control2" match-class="highlight">
</div>		
```

Any idea of what wrong ?

**Comment by ghiden** [comment]
cities.name surely won't work because cities is an array.
There is no such thing as cities.name in your object.
And, you can't do cities[0].name as we don't support array notations.

**Comment by obelich** [comment]
i have a profile.first_name and it dont working :(
