### ISSUE TITLE
Large data issues?

### ISSUE THREAD

**Issue by zakster82** [ghiden/angucomplete-alt#328]
Hi,

I'm using angucomplete with ~7500 local data records, and I've got a min-length of 3 before the search starts. It works great most of the time, but there is some data that even with 6 characters typed in, it only filters the records down to about 1700. At this point, the UI slows badly and it's several seconds before you can type another character. Are there any suggestions for handling this sort of volume? Perhaps a way to limit how many results are brought back?

Thanks,
Z

**Comment by ghiden** [comment]
We had to go through that kind of situations once before.
We did all sorts of optimizations but didn't help much.
So what we did at last was moving to React, just that part of UI.
It was a year and half ago.
Maybe there are better options out there now.
Probably moving to Angular2 and use something else, not this directive.

**Comment by Boshen** [comment]
You should just display the first dozen of matches. Changing it to React won't help because you still have to populate the DOM with 1700 nodes ...

**Comment by zakster82** [comment]
That's what I thought as well Boshen. I modified the code to only return the first 200 matches and the slow down problem went away completely. If users complain, I may have to revisit but for now I think that's a reasonable compromise.
