### ISSUE TITLE
show results that start with input instead of results that contain input

### ISSUE THREAD

**Issue by firoze** [ghiden/angucomplete-alt#332]
for example:
in the list of countries, searching "ba" would return "bahamas, bahrain..."  and not "albania, azerbaijan..."
should this be a feature request or is there a way to enforce this already?

thanks in advance! it's a really useful library :+1:

**Comment by ghiden** [comment]
I'm releasing a new version which allows you to write your own search function.
Could you play with this branch and see if it works or not?
https://github.com/ghiden/angucomplete-alt/tree/custom-local-search

Follow this issue to know how to use it:
https://github.com/ghiden/angucomplete-alt/issues/330

**Comment by firoze** [comment]
Thanks for pointing me to the branch, I'll take a look at it to see how I can get it to work on my project.
Will you be releasing this soon? (then `bower` can pick it up, otherwise I'd have to manually reference the file somehow)

**Comment by firoze** [comment]
I copied the entire `angucomplete-alt.js` file over manually to test, and the local-search directive works really well! I was able to write a separate (sort of simple) search function and it worked out fine. Will keep an eye out for the next release so I can add it to my `bower.json` (though I think it's ready because it's working just fine).

**Comment by ghiden** [comment]
@firoze Thanks for your feedback.
I'll try to release tonight (NZ time) if I'm not too tired.

**Comment by ghiden** [comment]
Released v2.2.0.
