### ISSUE TITLE
Call back function when user selects one category among 4 categories from the angucomplete dropdown

### ISSUE THREAD

**Issue by psuresh76** [ghiden/angucomplete-alt#334]
Hi Team,
I have used this angucomplete-alt functionality and displayed the drop down list as 3 categories like location name, state name, country name by calling the REST web service. Here I have one issue as below.

1. I need to call back the REST web service when user selects only country name category from the drop down list.

Please help me in this case.

Thanks,
Suresh P.

**Comment by Boshen** [comment]
### Description of attributes
| Attribute | Description | Required | Binding | Example  |
| :------------- |:-------------| :-----:| :-----:| :-----|
| selected-object | Either an object in your scope or callback function. If you set an object, it will be passed to the directive with '=' sign but it is actually one-way-bound data. So, setting it from your scope has no effect on input string. If you set a callback, it gets called when selection is made. To get attributes of the input from which the assignment was made, use this.$parent.$index within your function. [example](https://ghiden.github.io/angucomplete-alt/#example1) | Yes | = | selectedObject or objectSelectedCallback |

Use the callback function and do all your logic in it.
