### ISSUE TITLE
scrollbar bug when no id attribute is provided

### ISSUE THREAD

**Issue by fish520** [ghiden/angucomplete-alt#344]
I saw the scrollbar bug in issue#46 has been fixed, but when no id attribute is provided, the bug exists again, this bug makes the id attribute a required option. may be there has some problem with the following logical:

```javascrip
scope.hideResults = function() {
        if (mousedownOn &&
            (mousedownOn === scope.id + '_dropdown' ||
             mousedownOn.indexOf('angucomplete') >= 0)) {
          mousedownOn = null;
        }
```

**Comment by ghiden** [comment]
Id is required.
Have a look at the table: https://github.com/ghiden/angucomplete-alt#description-of-attributes
