### ISSUE TITLE
Cannot get required to work

### ISSUE THREAD

**Issue by psmod2** [ghiden/angucomplete-alt#345]
Hi,

I know this has been asked in several places however I just can't seem to get the required field to work.

My code as is look like:

```
<div class="float-left large-6 medium-7 small-12 columns">

<angucomplete-alt 
                     id="myFirstAutoComp"
                     pause="100"
                     selected-object="selectedCountry"
                     local-data="countries"
                     search-fields="name"
                     title-field="name"
                     input-class="form-control form-control-small"
                     input-name="countryReg"
                     field-required="true"
                     minlength="1"
 />

<div ng-messages="registrationForm.countryReg.$error" ng-if="registrationFormValid">
       <span class="postFormErrorMessage" ng-message="required">
         please enter your country</span>
</div>

</div>
```

Is there an issue or am I going wrong somewhere?

**Comment by ghiden** [comment]
Do you have a form controller somewhere in your parent nodes?

**Comment by psmod2** [comment]
Yes, all inputs are within that: 

`<form name="registrationForm" novalidate>`

That noValidate is to stop HTML5 field validation

**Comment by ghiden** [comment]
It looks legit to me.
Can you create a jsbin or plnkr example?

**Comment by psmod2** [comment]
Hi, Not a working copy as I haven't added the angucomplete js files however my code itself is a ditto of this: https://plnkr.co/edit/lVNOqLjKm1goCFIR67f7?p=preview

**Comment by psmod2** [comment]
So i used this to do some debugging:

```
<span ng-show="registrationForm.$valid" class="valid-status valid">
      [VALID]</span>
```
And it works however that ng-Messages or ng-Class i cannot get to work?

**Comment by ghiden** [comment]
It's "autocomplete-required" that you need to specify.
Here you go, a working example:
https://plnkr.co/edit/llMbYzwKz7WqAmKZQPHL?p=preview

**Comment by psmod2** [comment]
Thanks
