### ISSUE TITLE
question about using remote datasource

### ISSUE THREAD

**Issue by samwzm** [ghiden/angucomplete-alt#347]
Hi, there,

I am very interested in this component! I have a question and appreciate your help. I want to use remote datasource (like example 5) through rest call. The return format is json array. However, there is no root object, can I still use such kind of json format? I googled and found a post couple years ago, it said this component can't consume json array without root object. Can anyone confirm that? 

By the way, if it can, could anyone provide an example?

Thanks,
Sam

**Comment by ghiden** [comment]
Try not using remote-url-data-field, meaning not setting this field at all.

**Comment by ghiden** [comment]
@samwzm did it work?

**Comment by ghiden** [comment]
I believe it worked.
