### ISSUE TITLE
Some question for remote-api-hander.

### ISSUE THREAD

**Issue by LuciferZhang** [ghiden/angucomplete-alt#348]
Now I use remote-api-handler to get remote data from my own service. But It does not work!

html-code
                       `<div style="display: inline-block;"`
                             `angucomplete-alt id="materialKey"`
                             `pause="100"`
                             `remote-api-hander="searchApi"`
                             `selected-object="materialNameSelected"`
                             `search-fields="name"`
                             `title-field="name"`
                             `minlength="1"`
                             `input-class="form-control input-sm table-search"`
                             `match-class="highlight"`>`
                        `</div>`

controller-code
`$scope.searchApi = function (key) {`
        `MaterialService.find(key).$promise.then(function (res) {`
      ` });`
   `};`

service-code
    `this.find = function (key) {`
`        var resource = $resource(apiFindKeyUrl + "/:key");`
`        return resource.get({key: key});`
`    };`

**Comment by Zhang-Yida** [comment]
remote-api-hander="searchApi" to remote-api-handler="searchApi"

**Comment by ghiden** [comment]
@LuciferZhang are you happy with @Zhang-Yida's solution?
If so, please close this.

**Comment by ghiden** [comment]
I believe it's done.
