### ISSUE TITLE
parse-input not working

### ISSUE THREAD

**Issue by herman135** [ghiden/angucomplete-alt#351]
I use parse-input="parseInput()", but the function I add on the $scope is not called.
I have tried to use focus-in and it's working.

So, it's seems the angucomplete-alt not handling this attribute.

`<div 
			angucomplete-alt id="ex1"
  			placeholder="Search contact"
  			maxlength="255"
  			pause="200"
  			selected-object="selectedContact"
  			remote-url="/phone-book/top10?contact="
  			search-fields="phoneName"
  			title-field="phoneName"
  			description-field="phoneNumber"
  			minlength="1"
  			input-class="form-control form-control-small"
  			match-class="highlight"
  			input-name="contact"
  			field-required="true"
  			parse-input="parseInput()"
  			focus-in="focusIn()">
  		</div>`
`	    $root.parseInput = function(){
	    	console.log("parseInput called...");
	    }
`

**Comment by ghiden** [comment]
I've never seen that you can define a function under $root object.
Does it really work?
Usually, you inject $rootScope and define something under $rootScope.

**Comment by herman135** [comment]
I am sorry, somethings modify the $rootScope into $root during the copy-paste.
Of course the usage of $root not working :D

In my code I use $rootScope, but the parse-input attribute not working. The injected callback function doesn't called.

**Comment by ghiden** [comment]
What is not working?
parseInput is a function that needs to take a string and returns a string.
By the way, I should update the README on how to use parseInput.
If your parseInput is like you described, it won't do anything good but harm as it does not return anything.

**Comment by herman135** [comment]
I have try to use parseInput to take a string as input and returns a string.
`$rootScope.parseInput = function(data){ console.log("parseInput called..."); return data; } 
`
But the parseInput function still not called.

**Comment by ghiden** [comment]
What version of angucomplete-alt.js are you using?

**Comment by herman135** [comment]
I use 2.2.0 version from CDN https://cdnjs.cloudflare.com/ajax/libs/angucomplete-alt/2.2.0/angucomplete-alt.min.js

**Comment by ghiden** [comment]
parseInput is working as you can see in this example:
http://plnkr.co/edit/Gq0529?p=preview
If you create your example, I can have a look.

**Comment by herman135** [comment]
Yes, it's absolutely working.
I'v tried to copy and paste your code, but not working yet.

I think something wrong with my code.
But I know now that parse-input attribute is actually working.

So, thank you very much for your help.
