### ISSUE TITLE
Trouble displaying number of matches when searching through local files

### ISSUE THREAD

**Issue by alex-citizen** [ghiden/angucomplete-alt#352]
Hi,

I am trying to display the number of matches in the dropdown as the user types. My initial thought was to try to capture the results property which gets used to populate the dropdown, but I can't figure out how to do that. My data sources are local variables, so it looks like there's no opportunity to run a function after the results come back like there is with an API data source. 

Is there a way to count the matches that I'm overlooking?

**Comment by ghiden** [comment]
I don't think that's possible with the current exposed API.
