### ISSUE TITLE
Autocomplete in only a subset of the string

### ISSUE THREAD

**Issue by tiagoovieira** [ghiden/angucomplete-alt#353]
I have json file that I'm importing, that consists in a list of cities, each entry is formatted as such:
"city, district"

Is there a way to just autocomplete the first part of the string "city"? 
For example, If I type "New York", it will return a list of all the cities in New York, but what I really want to achieve is just one result "New York, New York"

**Comment by ghiden** [comment]
Sorry, that's not possible.
If it is the data you receive from a remote API, we have a response formatter with which you can transform your data.
But there is no such thing for local data.
The reason behind this is if the data is local, you should be able to transform freely.
I would probably have one more field in the data set just to hold city name.
