### ISSUE TITLE
Set default config

### ISSUE THREAD

**Issue by bissolli** [ghiden/angucomplete-alt#356]
Hi guys!

Is there any way to set the default config to the component? I would like to change the SEARCHING TEXT to everywhere but would like not to do something like:

`<div angucomplete-alt
  ...
  placeholder="Search projects"
  pause="500"
  text-searching="MY TEXT HERE"
  ...
  match-class="highlight">
</div>`

I would like to do something as on the angular select ui:

`var app = angular.module('app', ['ui.select']);

app.config(function(uiSelectConfig) {
  uiSelectConfig.theme = 'bootstrap';
});`

Somebody knows how to do that?

Thanks in advance!

**Comment by ghiden** [comment]
Nope, there is no such feature.
Sorry, this directive is not that sophisticated.

**Comment by gustavobissolli** [comment]
No problem!! It already helps a lot!

Great job!
