### ISSUE TITLE
Passing extra parameters to callback

### ISSUE THREAD

**Issue by quintenvk** [ghiden/angucomplete-alt#360]
Situation: i'm using the directive within `ng-repeat` (eg `ng-repeat="row in vm.items"`). I need to set certain parameters for a different object on the `row` that is passed within `ng-repeat`, so I'd like to be able to pass the `row`-object through an additional parameter. Right now I don't really have a clean way to re-use the value of the object (apart from maybe `row.autocomplete.originalObject.id` and then a few proxy-objects.

**Comment by quintenvk** [comment]
I managed to fix it by setting a function on `row` and using `row` within this function.
```
row = {};
row.doSelectedAction = function(selectedItem) {
     row.additionalData = selectedItem.originalObject.data;
};

item-changed="row.doSelectedAction"
```

**Comment by loren138** [comment]
I'm needing this as well.  Did you create a copy of the function for every row?

**Comment by quintenvk** [comment]
Yes, every row in the ng-repeat has a separate anonymous function assigned to it.

**Comment by loren138** [comment]
Still might be a good feature request, but I can do that.
