### ISSUE TITLE
Letters in th elist are not colored red

### ISSUE THREAD

**Issue by bojannyc** [ghiden/angucomplete-alt#367]
When I type text in the search box, list filter works fine, but the letters which are typed in the box are not colored red in the list, like in example? Am I missing something?

**Comment by ghiden** [comment]
Probably missing a css class? If you have match-class="highlight", define it something like this

```css
.highlight {
	color: #ff0000;
}
```

**Comment by bojannyc** [comment]
Yes, that was it. Many thanks ghiden.
