### ISSUE TITLE
Fuzzy search?

### ISSUE THREAD

**Issue by teacoat** [ghiden/angucomplete-alt#368]
I dont think this needs much explanation, but it would be great to have a fuzzy search option for when you have kinda complex strings;

eg. If i am sorting autocompleting gun names, AK-47 needs to be typed exactly like that rather than ak 47

**Comment by azrael-sub7** [comment]
Currently you can do just that if you use remote API, otherwise if you don't want to make a request i guess this feature may be needed in some cases.

**Comment by shashykant** [comment]
It need to be handled at remote API level. It isnt good always to expose ur business logic to the client side.

**Comment by ghiden** [comment]
Custom search capability is already exposed.
You can use local-search to pass your fuzzy search function.
There are various fuzzy search implementation.
Just google it and implement the one that fit your needs.
Here is one:
http://www.dustindiaz.com/autocomplete-fuzzy-matching

**Comment by teacoat** [comment]
Awesome thanks @ghiden thats just what I was looking for, somehow overlooked the local-search!
