### ISSUE TITLE
issue with API remoteURL

### ISSUE THREAD

**Issue by bojannyc** [ghiden/angucomplete-alt#369]
This is my config for API remote call:
angucomplete-alt id="search" placeholder="Search meta360 repository..." pause="100" selected-object="metaSearch"  remote-url="http://localhost:1337/api/searchAPI/" remote-url-data-field="data" search-fields="searchName" title-field="searchName"  image-field="url" minlength="1" input-class="form-control form-control-small mysearch" match-class="highlight">

The service returns data (4 records), I can see that in debugger, variable responseData in the function httpSuccessCallbackGen(str)...however, list is not populated with results????

![untitled](https://cloud.githubusercontent.com/assets/18403178/14498259/b9a11af8-0167-11e6-975a-67d8aca6a4c4.png)

**Comment by azrael-sub7** [comment]
If you access your API with the web browser what response do you get? 
I generate a response similar to this for one of my API: 
`[{"alte_detalii":"Bloc 5 scara 6 etaj 2 apartament 44","pid":"188"}] `
and the data is fetched. It works even if the json object is in an array just like above, post here what your API is returning maybe someone can help.

**Comment by bojannyc** [comment]
Just found the solution here - it is about to format response.
http://stackoverflow.com/questions/32251694/angucomplete-alt-remote-api-handler-not-working-as-expected
