### ISSUE TITLE
Custom Template

### ISSUE THREAD

**Issue by Kesymaru** [ghiden/angucomplete-alt#37]
Hello, nice module.

I want to use a custom template on the results dropdown, i think that maybe adding an attribute like: template="templateUrl" will be great.

This feature will be awesome to customize the way the results will look and event adding some extras feature without extra work.

**Comment by ghiden** [comment]
Already supported.

**Comment by ceovishnu** [comment]
is there a way to implement the when u type name then it's display the related category with new div with new hover.
if it possible then let me know.
