### ISSUE TITLE
Select text in input when clicked/focused

### ISSUE THREAD

**Issue by janoskaz** [ghiden/angucomplete-alt#371]
How do I select the text in `angucomplete-alt` tag?

I have this directive: 
```javascript
.directive('selectOnFocus', ['$window', function ($window) {
    return {
        restrict: 'A',
        link: function (scope, element, attrs) {
            element.on('focus', function () {
                if (!$window.getSelection().toString()) {
                    // Required for mobile Safari
                    this.setSelectionRange(0, this.value.length)
                }
            });
        }
    };
}])
```

And I use it like this:

```html
<div angucomplete-alt
  placeholder="Search"
  pause="100"
  selected-object="modelvalue"
  local-data="countries"
  search-fields="name"
  title-field="name"
  select-on-focus
</div>
```

It selects text in input or textarea, when they are focused or clicked into. I wish to use this functionality with `angucomplete-alt`. When I click into `angucomplete-alt`, I get error `TypeError: this.value is undefined`. This, however, works with both input and textarea.

**Comment by ghiden** [comment]
angucomplete-alt creates input element internally. So, you can't call this directive onto that input field.
You need to fork it and add this capability into the directive.

**Comment by bonucci** [comment]
@janoskaz you can customize the angucomplete-alt.js by adding in template "ng-focus="onFocusHandler($event)"  $event parameter  and than change the scope.onFocusHandler to something like  ```
scope.onFocusHandler = function($event) {
          //custom implementation
          $event.target.select(); ...
```
