### ISSUE TITLE
Trouble with remote-api-handler

### ISSUE THREAD

**Issue by ekDotNet** [ghiden/angucomplete-alt#376]
I have tried everything I can think of to get the remote api handler to work properly with no success.  I am trying to call an Angular service to get the data based on the input string that is typed in.  This is a large data set and would be inefficient to get the full list initially.

I am wondering if I am not tying the result set to the markup properly?  The success call back method is hit and populates the result set as expected, however the results never display in the UI.  

<angucomplete-alt id="ex1"
                                      placeholder="Search prospects"
                                      pause="100"
                                      selected-object="lpCtrl.selectProspect"
                                      remote-api-handler="lpCtrl.getProspectList"
                                      search-fields="FirstName,LastName,Address1"
                                      title-field="FirstName,LastName,Address1"
                                      minlength="3"
                                      input-changed="lpCtrl.selectedProspectChanged"
                                      input-class="form-control form-control-small"
                                      text-searching="gettin it..."
                                      text-no-results="dumb search" />

vm.getProspectList = function(){
        prospectDataService.getProspects().then(onGetProspectsSuccess, onGetProspectsFailure);
    }

**Comment by ghiden** [comment]
Missing a return.

**Comment by ekDotNet** [comment]
Thank you.  This worked.
