### ISSUE TITLE
Search by Title and Description(both) does not work with API calls

### ISSUE THREAD

**Issue by bojannyc** [ghiden/angucomplete-alt#383]
I am trying to put both, title and description field in  "search-fields", but it does not work with api call... Any idea?

`<div  angucomplete-alt id="ex71" placeholder="Search meta360 repository..." pause="100" selected-object="metaSearch"  remote-url="http://localhost:1337/api/searchAPI/" remote-url-data-field="data"   search-fields="searchText, description" title-field="searchText" description-field="description" image-field="url" minlength="1" input-class="form-control form-control-small mysearch" clear-selected="true" match-class="highlight">
        </div>`

**Comment by ghiden** [comment]
You probably need to set remote-url-request-formatter.
In this GitHub example, I have the formatter set to the following:
```js
$scope.remoteUrlRequestFn = function(str) {
  return {q: str};
};
```
http://ghiden.github.io/angucomplete-alt/#example5

**Comment by bojannyc** [comment]
I'm getting 404 when I include  remote-url-request-formatter with this code...

**Comment by ghiden** [comment]
It's just an example.
I don't know how your API works. So, adjust it to fit your needs.
