### ISSUE TITLE
How I can get title from result without js(just with your lib param)?

### ISSUE THREAD

**Issue by Ashalbulk** [ghiden/angucomplete-alt#399]
Now I get 
```
city:[{
$$hashKey:"object:24",
description:undefined,
image:"",
originalObject:Object,
title:"Москва",
__proto__:Object}]
```
But I want get just `city:"Москва"`

Your lib is perfect but this is big problem for me.

Thanks

**Comment by ghiden** [comment]
Here is how:
```js
[your selectedObject].title
```

**Comment by Ashalbulk** [comment]
nope, not in controller. I want set to selectedObject not object, only title from this object.

**Comment by ghiden** [comment]
Use callback. 
https://ghiden.github.io/angucomplete-alt/#example7
