### ISSUE TITLE
Why no 2 way binding?

### ISSUE THREAD

**Issue by boldtrn** [ghiden/angucomplete-alt#400]
Thanks @ghiden for this great lib. I have just one minor question. Why are you against a 2 way binding? I have seen from other issues that people are eager for that function (including me). Would it hurt to add an option like `enable2wayBinding`?

**Comment by Jesus82** [comment]
There was a commit about enabling ng-model, but I wasn't able to make that work in my project :(
[](https://github.com/ghiden/angucomplete-alt/pull/338/commits)

**Comment by ghiden** [comment]
There are lots of discussion about this, so just search issues if you want to know.
My position is still no.
The original directive angucomplete didn't have 2-way binding.
And, I kept adding features on top of this foundation.
So, enabling 2-way binding and keeping all the features in tact is probably quite difficult.

**Comment by boldtrn** [comment]
@ghiden Thanks for your reply. I've seen the other issues but wasn't satisfied with the answers. I just don't understand it, since it won't break any existing code if we would add a switch that enables 2-way binding. Maybe if a user decides to use 2-way binding one or two features stop working. Then we have to document it and every user can decide if he/she wants it or not. I just think the idea of angular is to allow a 2-way binding. But with angucomplete I somehow don't see the benefit of using angular at all, since I have to set and get the values by hand, as I would with jQuery.

Thanks in advance
