### ISSUE TITLE
How to add search icon on the right  in angucomplete-alt box?

### ISSUE THREAD

**Issue by bojannyc** [ghiden/angucomplete-alt#411]
Any help will be greatly appreciated.

**Comment by ghiden** [comment]
Using css is the easiest.
If you want somewhat complex design, you need to provide your own template along with your css.

**Comment by bojannyc** [comment]
Can you please give some example?

**Comment by ghiden** [comment]
Sorry, I don't have time for this.
It's not complex. It's just css.
