### ISSUE TITLE
Result is showed in very short space time

### ISSUE THREAD

**Issue by gfamorimo** [ghiden/angucomplete-alt#419]
Hi guys, sorry about my poor english.

I have tried to use the angucomplete with remote api handler how you can see below:

`<angucomplete-alt id="input-filtro-restricoes2"
                                                                              placeholder="« Selecione »"
                                                                              pause="400"
                                                                              selected-object="editarUsuCtrl.restricaoSelecionada"
                                                                              remote-api-handler="editarUsuCtrl.recuperaValorQueryListagem"
                                                                              title-field="descricao"
                                                                              search-fields="descricao"
                                                                              title-field="descricao"
                                                                              input-class="form-control"
                                                                              minlength="1"
                                                                              text-searching="Pesquisando..."
                                                                              text-no-results="Nenhum registro encontrado."
                                                                              initial-value="editarUsuCtrl.novaRestricao.identificador"
                                                                              match-class="highlight"/>`

`vm.recuperaValorQueryListagem = function(filtro, timeoutPromise){
        //return ClasseService.retornaValorQueryListagem(vm.novaRestricao.classeAplicacao.classe.id, filtro);
        return $http.get('rest/classes/' + vm.novaRestricao.classeAplicacao.classe.id +'/listagem' ,{
            params : { filtro : filtro, cacheKill: Date.now()+Math.random(), timeout: timeoutPromise}
        });
    }`

How you can see, the method return a list with object, but the result is showed in very short space of time.

![image](https://cloud.githubusercontent.com/assets/3053465/16924475/e3c07b24-4cf5-11e6-8cb6-f4692d0805a9.png)

What I did wrong?

**Comment by Boshen** [comment]
What do you mean by "very short space of time"?

**Comment by gfamorimo** [comment]
The result is showed for just a 1 second.

**Comment by Boshen** [comment]
Your code looks fine. You'll need to debug it yourself :-(

**Comment by gfamorimo** [comment]
I found the problem origin.
Block ui was firing and how the response from my backend is fast the block ui was not showing the loading animation.
