### ISSUE TITLE
How to provide full path into image-field

### ISSUE THREAD

**Issue by lavkesh1608** [ghiden/angucomplete-alt#423]
Hi ,
I am having a json data that have only image name and i want concatenate image name with path into image-field.Is there any callback function for this?

Please solve this or provide me any suggestion , i cant put full path into my database so that image-field works directlty.

My code is as below:
`<angucomplete-alt id="invite-angucomplete-alt"
                    placeholder="Enter email"
                    pause="100"
                    selected-object="selectedUser"
                    remote-url="/api/getUsersByQuery"
                    remote-url-request-formatter="remoteUrlRequestFn"
                    remote-url-data-field="data"
                    title-field="displayName"
                    minlength="2"  
                    image-field="path+imageFile"**
                    input-changed="inputChangedFn"
                    match-class="highlight"
                    input-class="form-control invite-input"/>`

**Comment by ghiden** [comment]
Try remote-url-response-formatter.

**Comment by lavkesh1608** [comment]
Hi Hidenari,

Thanks so much for your quick reply. This solved my problem. Here is what i did , it works :


`$scope.searchResponseFormatter=function(response){
			if(response.data.length>0){
				angular.forEach(response.data,function(value,key){
					if(value.imageFile!=''){

						response.data[key].imageFile='companies/'+$scope.authentication.user.folderName+'/'+value.imageFile;
					}else{
						
						//default image
						response.data[key].imageFile='modules/core/img/user_img.png';
					}

				});
				return item;
			}else{

				return item;

			}		

		}`
