### ISSUE TITLE
Doesn't work when typing in Japanese

### ISSUE THREAD

**Issue by nhim175** [ghiden/angucomplete-alt#429]
Steps to reproduce:
- Type some Japanese words to search.
- As soon as you press enter or space to finish the word, the result is empty no matter what you typed in.

Browser: Any
OS: Mac 10.11.5

**Comment by nhim175** [comment]
PR here: https://github.com/ghiden/angucomplete-alt/pull/430
Please check when you have time. Thanks!

**Comment by ghiden** [comment]
merged
