### ISSUE TITLE
How Manually I can set the value in textbox?

### ISSUE THREAD

**Issue by msgadi** [ghiden/angucomplete-alt#461]
`$http({
        method: 'GET',
        url: '/GetCountries'
    }).then(function (data) {
        $scope.countries= data;
    }, function () {
        alert("error");
    }) 
 $scope.Activities = {  Name: "India", code"IN" };
`

I want to show one item  in textbox on initial load..Is there anyway??

**Comment by ghiden** [comment]
Use initial-value field.
https://ghiden.github.io/angucomplete-alt/#example9
