### ISSUE TITLE
Throw an error when handling number data

### ISSUE THREAD

**Issue by ghiden** [ghiden/angucomplete-alt#47]
When given data is an array of number, it throws an error.

**Comment by DavidVentura** [comment]
News on this? At the moment, if I use a number (code) to filter, angucomplete-alt breaks totally (doesn't pop up, autocomplete, nothing). At least use a toString() to allow us to filter by numbers, I'll check if I can PR this

**Comment by DavidVentura** [comment]
Ok, it was pretty simple, I won't do a PR, but please fix this.
Line 447, change
```
            match = match || (value.toLowerCase().indexOf(str.toLowerCase()) >= 0);
```
To
```
            match = match || (value.toString().toLowerCase().indexOf(str.toLowerCase()) >= 0);
```

You are assuming a string (toLowerCase), but it won't work on numbers.

**Comment by trsrm** [comment]
Bug still exists

**Comment by ghiden** [comment]
@trsrm Could you create a jsbin or plnkr example that shows this is still causing issues?
