### ISSUE TITLE
How to clear data field when user deletes selected value

### ISSUE THREAD

**Issue by Trish00** [ghiden/angucomplete-alt#50]
I have an auto complete text box set up.  (using angucomplete-alt)

If the user selects a value everything works fine.

But if a user selects a value, and then deletes it, the data model retains the selected value.

I have tried ng-change and ng-blur but neither work.

I don't want to clear the field after the selection is made so how do I capture it when the user clears the selected item?  

Thanks

**Comment by thrinay** [comment]
May I please know how this issue is resolved? Because at the moment am facing the same issue. Whenever am clearing an input field and making a post request I can see that there is no change being reflected and it keeps the same value as before without updating empty strings.

**Comment by vishalsahni** [comment]
I also need the solution related to this issue.

Please send it at my email id .

**Comment by thrinay** [comment]
You can attach a callback function to selected-object and you can manipulate the changes in that function. I have done that and it resolved my problem

**Comment by peidong-hu** [comment]
I am using the selected-object callback, but the parameter 'selected' is always 'undefined' if user doesn't select a value from the dropdown list on UI.

How can I know if the user set the value as empty on UI in autocomplete-alt?
