### ISSUE TITLE
Explicit tabindex

### ISSUE THREAD

**Issue by mschaeuble** [ghiden/angucomplete-alt#57]
When trying to set an explicit tabindex to an angucomplete-alt annotated div element, the tabindex applies to the div and not the input field. This prevents input to the input field when navigating through the form with TAB. Is there a way to set an explicit tabindex on the (generated) input field?

**Comment by schrizsz** [comment]
+1

**Comment by simonpeters** [comment]
+ 1

**Comment by walaqi** [comment]
+1

**Comment by ghiden** [comment]
Released v2.2.0.
