### ISSUE TITLE
Scrollbar Bug

### ISSUE THREAD

**Issue by Kisama** [ghiden/angucomplete-alt#63]
I found a bug in scroll bar.
In the example-1, when the example page's scroll is top, autocomplete's scroll bar works 
![autocomplete-scoll-work](https://cloud.githubusercontent.com/assets/368174/4623080/ec41d44c-5345-11e4-992b-fb0c73984653.png)

but when the example page's scroll is not top like below image and autocomplete's scroll bar is moved, sometimes the autocomplete list is disappear. 
![autocomplete-scoll-not-work](https://cloud.githubusercontent.com/assets/368174/4623079/ec36933e-5345-11e4-803a-f8b429f7203f.png)

**Comment by fmccown** [comment]
This is still an issue in Win 8.1 latest version of Chrome (43.0.2357.130 m) and IE (11.0).  You can easily verify by viewing the examples page and scrolling down a little and trying to move the thumb in the Example 1 list.

**Comment by ghiden** [comment]
@fmccown Thank you for reporting. It's a regression bug. I think when I fixed the other issues related with blur events a few releases back, this one probably came back.
