### ISSUE TITLE
change remote data to post?

### ISSUE THREAD

**Issue by ajmajma** [ghiden/angucomplete-alt#79]
I need to change the remote call to a post (not a get) and prime some data I think I should use remote-url-request-formatter to do this, however I cant seem to get it working. I'm basically just trying to post to the provided url with the typed data send under a key of "keywords:", is something like this possible with your version of this? I had no problem with the original, but I had to actually change it in the search timercompletefunction in his setup. Thanks!

**Comment by sijabbour** [comment]
My company made a decision to only allow POST calls to their APIs. A version that supports POST would be great.

**Comment by ghiden** [comment]
v0.0.41 has a new feature to define custom http handler.
So you can create your POST request function.
Please have a look.
