### ISSUE TITLE
Required support

### ISSUE THREAD

**Issue by vcuca** [ghiden/angucomplete-alt#8]
Hi,
is there support for required attribute?

**Comment by ivanstojkovicapps** [comment]
for me it doesn't work. I have something like this:

<angucomplete-alt id="client" input-name="client_name" placeholder="Enter client name" pause="100" initial-value="{{selectedClient == null ? '' : selectedClient.name}}" selected-object="SelectedClientHandler" local-data="clients" search-fields="name" title-field="name" minlength="0" field-required="true" input-class="form-control form-control-small {{(new_entry_form.submitted && new_entry_form.client_name.$error.required) ? 'red-border' : ''}}"/>

**Comment by ivanstojkovicapps** [comment]
You need something like this in line 51 in angucomplete-alt.js

required="{{fieldRequired == \'true\' ? \'required\' : \'\'}}"
