### ISSUE TITLE
Is there a way to set the value of the input?

### ISSUE THREAD

**Issue by chenkirk** [ghiden/angucomplete-alt#82]
First of all, thank you for such a great fork of the angucomplete module.

I am currently using it with selected-object set as a function because I need to know when the input changed. This means I can't 2-way bind it to a variable. I am trying to set the value of the input after the input has initialized. Is there a way to do this?

**Comment by elifio** [comment]
You may help this ...

I have solved.
I do not like but it works.
I only use de input to show the name... then i get the id ... when is selected in another scope var


using dom id :(

var i = angular.element('#nameAutocomplete_value');
i[0].value = $scope.var.description.;

**Comment by ghiden** [comment]
Use initial-value with object.
