### ISSUE TITLE
Can we trigger angucomplete do a searching ??

### ISSUE THREAD

**Issue by htatuan** [ghiden/angucomplete-alt#84]
I have 2  autocomplete controls call them as A & B  that are using yours..
I have a only one list item for them. Item includes {Name , Value}. Means that both A and B have one source. A will display name, and B will display Value. When A is changing, so B is either.
 
A will search by Name. After A done the searching. A displays the Name and B displays  Value of A
B will search by Value. After B done the  searching. B displays the Value and A displays Name of B
Can we do that?
I really love your directive. Hope you can support me soonest :) 
Regards,

**Comment by ghiden** [comment]
Not an issue I believe.
