### ISSUE TITLE
Multi-select support

### ISSUE THREAD

**Issue by sanketi** [ghiden/angucomplete-alt#89]
Is there a way to support multi select (choosing more than one selected value) with this directive?

**Comment by MartinNuc** [comment]
We made a fork of angucomplete and implemented multi select using `selected-object` field. Basically function specific in this field receives selected item but the select of angucomplete remains opened so you can pick another item. I will post PR for others if they need this functionality.

**Comment by MartinNuc** [comment]
PR is here: https://github.com/ghiden/angucomplete-alt/pull/312
