### ISSUE TITLE
First match automatically gets focused

### ISSUE THREAD

**Issue by clicktravel-harpreet** [ghiden/angucomplete-alt#92]
Can you add the same feature to automatically focus the first match from the dropdown list like the angular bootstrap ui typeahead?

http://angular-ui.github.io/bootstrap/#/typeahead
typeahead-focus-first (Defaults: true) : Should the first match automatically be focused as you type

**Comment by kaseOga** [comment]
+1

**Comment by kaseOga** [comment]
Actually i'm using this:

    scope.$watch('results', function() {
        $('.searcher').nanoScroller({alwaysVisible: true, contentClass: 'scroll'});
        if(scope.results && scope.results.length > 0) {
            scope.currentIndex = 1;
        }
    });

In some cases, it select the 2nd position instead the 1st

**Comment by Freezystem** [comment]
+1
